<a href="https://colab.research.google.com/github/Of-Calls/sisicallcall-verification-finetuning/blob/main/titanet_medium_train_eval_colab_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TitaNet-Small Medium Train + Eval Colab v1

- 전체 Drive 마운트: `from google.colab import drive; drive.mount('/content/drive')`
- 데이터: `titanet_local_subset_medium.zip`
- 학습: TitaNet-Small / 5epoch / lr=5e-5 / batch_size=32
- 평가: baseline vs medium fine-tuned / 전체 80,000 trials
- 결과 저장:
  - 학습: `화자검증 데이터/titanet_finetune_runs/{RUN_ID}`
  - 평가: `화자검증 데이터/titanet_eval_runs/{EVAL_RUN_ID}`

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
from datetime import datetime

DRIVE_DATA_DIR = Path(
    "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터"
)
DATA_ZIP_PATH = DRIVE_DATA_DIR / "titanet_local_subset_medium.zip"

BASELINE_MODEL_NAME = "titanet_small"
MAX_EPOCHS = 5
LEARNING_RATE = 5e-5
BATCH_SIZE = 16
NUM_WORKERS = 2
PRECISION = "16-mixed"
SEED = 42


MAX_AUDIO_DURATION = 8.0
MIN_AUDIO_DURATION = 0.5

LIMIT_TRAIN_ROWS = 0
LIMIT_VALID_ROWS = 0
LIMIT_TRAIN_BATCHES = 1.0
LIMIT_VAL_BATCHES = 1.0

RUN_EVAL_AFTER_TRAIN = True
MAX_TRIALS_PER_ENROLL_SEC = 0
TARGET_FARS = [0.01, 0.05, 0.10]

RUN_ID = datetime.now().strftime("titanet_medium_5epoch_lr5e5_%Y%m%d_%H%M%S")
EVAL_RUN_ID = datetime.now().strftime("eval_medium_5epoch_lr5e5_%Y%m%d_%H%M%S")

DRIVE_TRAIN_SAVE_DIR = DRIVE_DATA_DIR / "titanet_finetune_runs" / RUN_ID
DRIVE_EVAL_SAVE_DIR = DRIVE_DATA_DIR / "titanet_eval_runs" / EVAL_RUN_ID
DRIVE_TRAIN_SAVE_DIR.mkdir(parents=True, exist_ok=True)
DRIVE_EVAL_SAVE_DIR.mkdir(parents=True, exist_ok=True)

print("DRIVE_DATA_DIR:", DRIVE_DATA_DIR, DRIVE_DATA_DIR.exists())
print("DATA_ZIP_PATH:", DATA_ZIP_PATH, DATA_ZIP_PATH.exists())
print("DRIVE_TRAIN_SAVE_DIR:", DRIVE_TRAIN_SAVE_DIR)
print("DRIVE_EVAL_SAVE_DIR:", DRIVE_EVAL_SAVE_DIR)

assert DRIVE_DATA_DIR.exists(), DRIVE_DATA_DIR
assert DATA_ZIP_PATH.exists(), DATA_ZIP_PATH

DRIVE_DATA_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터 True
DATA_ZIP_PATH: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_local_subset_medium.zip True
DRIVE_TRAIN_SAVE_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940
DRIVE_EVAL_SAVE_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_medium_5epoch_lr5e5_20260502_070940

In [ ]:
INSTALL_OR_REPAIR = False

if INSTALL_OR_REPAIR:
    !pip install -q "nemo_toolkit[asr]"
    !pip uninstall -y numpy
    !pip install --no-cache-dir --force-reinstall "numpy==1.26.4"
    print("설치/복구 완료. 런타임 재시작 후 처음부터 다시 실행하세요.")
else:
    print("Skip install/repair.")

Skip install/repair.

In [ ]:
import os, sys, json, ast, random, shutil, zipfile, gc
from pathlib import Path
from collections import defaultdict, Counter

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import soundfile as sf
from tqdm.auto import tqdm

import lightning.pytorch as pl
from lightning.pytorch.callbacks import ModelCheckpoint, LearningRateMonitor
from lightning.pytorch.loggers import CSVLogger
from omegaconf import OmegaConf, open_dict
from nemo.collections.asr.models import EncDecSpeakerLabelModel

try:
    from torchmetrics.classification import MulticlassAccuracy
except Exception:
    MulticlassAccuracy = None

print("python:", sys.version)
print("numpy:", np.__version__)
print("torch:", torch.__version__)
print("cuda:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)
print("lightning.pytorch:", pl.__version__)

pl.seed_everything(SEED, workers=True)
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

[NeMo W 2026-05-02 07:09:56 megatron_init:62] Megatron num_microbatches_calculator not found, using Apex version.
WARNING:nv_one_logger.api.config:OneLogger: Setting error_handling_strategy to DISABLE_QUIETLY_AND_REPORT_METRIC_ERROR for rank (rank=0) with OneLogger disabled. To override: explicitly set error_handling_strategy parameter.
WARNING:nv_one_logger.training_telemetry.api.training_telemetry_provider:No exporters were provided. This means that no telemetry data will be collected.
[NeMo W 2026-05-02 07:09:58 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\('
      m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)

[NeMo W 2026-05-02 07:09:58 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\('
      m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)

[NeMo W 2026-05-02 07:09:58 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\('
      elif re.match('(flt)p?( \(default\))?$', token):

[NeMo W 2026-05-02 07:09:58 nemo_logging:364] /usr/local/lib/python3.12/dist-packages/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\('
      elif re.match('(dbl)p?( \(default\))?$', token):

INFO: Seed set to 42
INFO:lightning.fabric.utilities.seed:Seed set to 42

python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
numpy: 1.26.4
torch: 2.10.0+cu128
cuda: True
gpu: NVIDIA A100-SXM4-40GB
lightning.pytorch: 2.4.0

In [ ]:
WORK_ZIP = Path("/content/titanet_local_subset_medium.zip")
EXTRACT_ROOT = Path("/content/titanet_medium_extract")

if EXTRACT_ROOT.exists():
    shutil.rmtree(EXTRACT_ROOT)
EXTRACT_ROOT.mkdir(parents=True, exist_ok=True)

if not WORK_ZIP.exists() or WORK_ZIP.stat().st_size != DATA_ZIP_PATH.stat().st_size:
    print("Copy dataset ZIP to /content ...")
    shutil.copy2(DATA_ZIP_PATH, WORK_ZIP)
else:
    print("Dataset ZIP already copied:", WORK_ZIP)

with zipfile.ZipFile(WORK_ZIP, "r") as zf:
    names = zf.namelist()
    print("ZIP first 30 entries:")
    for n in names[:30]:
        print(" -", n)
    zf.extractall(EXTRACT_ROOT)

candidates = []
if (EXTRACT_ROOT / "manifests").is_dir() and (EXTRACT_ROOT / "wavs").is_dir():
    candidates.append(EXTRACT_ROOT)
for p in EXTRACT_ROOT.rglob("*"):
    if p.is_dir() and (p / "manifests").is_dir() and (p / "wavs").is_dir():
        candidates.append(p)

candidates = sorted(set(candidates), key=lambda x: len(str(x)))
print("Dataset candidates:", candidates)
if not candidates:
    print("Extract root children:", list(EXTRACT_ROOT.iterdir()))
    raise FileNotFoundError("Could not find dataset dir with manifests/ and wavs/.")

DATA_DIR = candidates[0]
MANIFEST_DIR = DATA_DIR / "manifests"
COLAB_MANIFEST_DIR = DATA_DIR / "manifests_colab"
COLAB_MANIFEST_DIR.mkdir(exist_ok=True)

print("DATA_DIR:", DATA_DIR)
print("MANIFEST_DIR:", MANIFEST_DIR)
print("Manifest files:", [p.name for p in MANIFEST_DIR.iterdir()][:30])

Copy dataset ZIP to /content ...
ZIP first 30 entries:
 - manifests/enrollment_manifest_local.csv
 - manifests/evaluation_verification_manifest_local.csv
 - manifests/eval_manifest.json
 - manifests/train_manifest.json
 - manifests/trials_local.csv
 - manifests/valid_manifest.json
 - reports/audio_check_report.csv
 - reports/auto_shrink_report.json
 - reports/export_titanet_local_subset.log
 - reports/extracted_files.csv
 - reports/failed_extracts.csv
 - reports/speaker_distribution_report.csv
 - reports/split_leakage_report.json
 - reports/trial_distribution_report.csv
 - wavs/eval/0036/A0001-0036F1411-10000000-00009126_46676df7ac.wav
 - wavs/eval/0036/A0002-0036F1411-10000010-00010349_ac3a51cdc7.wav
 - wavs/eval/0036/A0002-0036F1411-10000040-00010325_928f24d51a.wav
 - wavs/eval/0036/A0006-0036F1411-10000010-00016739_fd4d7321e7.wav
 - wavs/eval/0036/A0016-0036F1411-10000010-00017850_1694def51f.wav
 - wavs/eval/0036/A0027-0036F1411-10000020-00066643_e6d9769310.wav
 - wavs/eval/0036/A0028-0036F1411-10000000-00066884_d4f915b79d.wav
 - wavs/eval/0036/A0050-0036F1411-10000040-00094807_8cb40e5c65.wav
 - wavs/eval/0036/A0060-0036F1411-10000000-00359767_b1fba1ccf8.wav
 - wavs/eval/0036/A0070-0036F1411-10000000-00384946_2626ce9e88.wav
 - wavs/eval/0036/A0076-0036F1411-10000020-00433099_ef42725903.wav
 - wavs/eval/0036/A0093-0036F1411-10000020-00492554_084cad4ed4.wav
 - wavs/eval/0036/A0097-0036F1411-10000010-00494501_e26a9abf5f.wav
 - wavs/eval/0036/A0097-0036F1411-10000020-00494231_f66431a419.wav
 - wavs/eval/0036/A0111-0036F1411-10000010-00508122_c8170748e7.wav
 - wavs/eval/0036/A0118-0036F1411-10000010-00529888_d0c7f458fd.wav
Dataset candidates: [PosixPath('/content/titanet_medium_extract')]
DATA_DIR: /content/titanet_medium_extract
MANIFEST_DIR: /content/titanet_medium_extract/manifests
Manifest files: ['valid_manifest.json', 'evaluation_verification_manifest_local.csv', 'train_manifest.json', 'trials_local.csv', 'enrollment_manifest_local.csv', 'eval_manifest.json']

In [ ]:
# =========================
# 5. JSONL utilities - fixed
# =========================
def read_json_objects_robust(path):
    """
    Handles:
    1. normal JSONL:
       {"a":1}
       {"a":2}

    2. concatenated JSON objects:
       {"a":1}{"a":2}

    3. comma-separated JSON objects:
       {"a":1},{"a":2}

    4. JSON array:
       [{"a":1}, {"a":2}]
    """
    path = Path(path)
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []

    # Case 1: whole file is valid JSON array
    try:
        obj = json.loads(text)
        if isinstance(obj, list):
            return obj
        if isinstance(obj, dict):
            return [obj]
    except json.JSONDecodeError:
        pass

    rows = []
    decoder = json.JSONDecoder()
    idx = 0
    n = len(text)

    while idx < n:
        # skip whitespace and common separators
        while idx < n and text[idx] in " \t\r\n,[]":
            idx += 1

        if idx >= n:
            break

        # if broken separator, move to next JSON object
        if text[idx] not in "{[":
            next_obj = text.find("{", idx)
            if next_obj == -1:
                break
            idx = next_obj

        try:
            obj, next_idx = decoder.raw_decode(text, idx)
            rows.append(obj)
            idx = next_idx
        except json.JSONDecodeError as e:
            print(f"[JSON decode failed] path={path}")
            print(f"index={idx}, near text:")
            print(text[idx:idx+500])
            raise e

    return rows


def read_jsonl(path, limit=None):
    path = Path(path)
    rows = []

    # First try strict JSONL
    try:
        with open(path, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, start=1):
                line = line.strip()
                if not line:
                    continue

                # tolerate trailing comma in each line
                if line.endswith(","):
                    line = line[:-1].strip()

                # skip JSON array brackets if accidentally present
                if line in ["[", "]"]:
                    continue

                rows.append(json.loads(line))

                if limit is not None and len(rows) >= limit:
                    break

        return rows

    except json.JSONDecodeError:
        print(f"[WARN] Strict JSONL failed. Trying robust parser: {path}")
        rows = read_json_objects_robust(path)
        if limit is not None:
            rows = rows[:limit]
        return rows


def write_jsonl(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


print("JSONL utilities fixed and ready.")

JSONL utilities fixed and ready.

In [ ]:
# =========================
# Repair: create train_manifest_colab.json if missing
# =========================
from pathlib import Path
import json

print("DATA_DIR:", DATA_DIR)
print("MANIFEST_DIR:", MANIFEST_DIR)
print("COLAB_MANIFEST_DIR:", COLAB_MANIFEST_DIR)

COLAB_MANIFEST_DIR.mkdir(exist_ok=True)

LOCAL_ROOT_MARKERS = [
    "D:/aihub_check/titanet_local_subset_medium",
    r"D:\aihub_check\titanet_local_subset_medium",
]
COLAB_ROOT_STR = str(DATA_DIR).replace("\\", "/")


def rewrite_path_to_colab(path_str):
    if path_str is None:
        return path_str

    s = str(path_str).replace("\\", "/")

    for marker in LOCAL_ROOT_MARKERS:
        m = marker.replace("\\", "/")
        if s.startswith(m):
            return s.replace(m, COLAB_ROOT_STR, 1)

    if s.startswith("/content/"):
        return s

    idx = s.find("/wavs/")
    if idx >= 0:
        return COLAB_ROOT_STR + s[idx:]

    return s


def read_json_objects_robust(path):
    path = Path(path)
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []

    try:
        obj = json.loads(text)
        if isinstance(obj, list):
            return obj
        if isinstance(obj, dict):
            return [obj]
    except json.JSONDecodeError:
        pass

    rows = []
    decoder = json.JSONDecoder()
    idx = 0
    n = len(text)

    while idx < n:
        while idx < n and text[idx] in " \t\r\n,[]":
            idx += 1

        if idx >= n:
            break

        if text[idx] not in "{[":
            next_obj = text.find("{", idx)
            if next_obj == -1:
                break
            idx = next_obj

        obj, next_idx = decoder.raw_decode(text, idx)
        rows.append(obj)
        idx = next_idx

    return rows


def read_jsonl(path, limit=None):
    path = Path(path)
    rows = []

    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()

                if not line:
                    continue

                if line.endswith(","):
                    line = line[:-1].strip()

                if line in ["[", "]"]:
                    continue

                rows.append(json.loads(line))

                if limit is not None and len(rows) >= limit:
                    break

        return rows

    except json.JSONDecodeError:
        rows = read_json_objects_robust(path)
        return rows[:limit] if limit is not None else rows


def write_jsonl(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def rewrite_jsonl_manifest(src, dst):
    rows = read_jsonl(src)
    missing = 0

    for row in rows:
        row["audio_filepath"] = rewrite_path_to_colab(row.get("audio_filepath"))

        if not Path(row["audio_filepath"]).exists():
            missing += 1

    write_jsonl(dst, rows)

    return {
        "src": str(src),
        "dst": str(dst),
        "rows": len(rows),
        "missing_paths": missing,
    }


rewrite_reports = []

for src_name, dst_name in [
    ("train_manifest.json", "train_manifest_colab.json"),
    ("valid_manifest.json", "valid_manifest_colab.json"),
    ("eval_manifest.json", "eval_manifest_colab.json"),
]:
    src = MANIFEST_DIR / src_name
    dst = COLAB_MANIFEST_DIR / dst_name

    assert src.exists(), f"missing source manifest: {src}"

    report = rewrite_jsonl_manifest(src, dst)
    rewrite_reports.append(report)

print(json.dumps(rewrite_reports, ensure_ascii=False, indent=2))

for report in rewrite_reports:
    assert report["missing_paths"] == 0, report

SOURCE_TRAIN_MANIFEST = COLAB_MANIFEST_DIR / "train_manifest_colab.json"
assert SOURCE_TRAIN_MANIFEST.exists(), SOURCE_TRAIN_MANIFEST

print("OK:", SOURCE_TRAIN_MANIFEST)

DATA_DIR: /content/titanet_medium_extract
MANIFEST_DIR: /content/titanet_medium_extract/manifests
COLAB_MANIFEST_DIR: /content/titanet_medium_extract/manifests_colab
[
  {
    "src": "/content/titanet_medium_extract/manifests/train_manifest.json",
    "dst": "/content/titanet_medium_extract/manifests_colab/train_manifest_colab.json",
    "rows": 72000,
    "missing_paths": 0
  },
  {
    "src": "/content/titanet_medium_extract/manifests/valid_manifest.json",
    "dst": "/content/titanet_medium_extract/manifests_colab/valid_manifest_colab.json",
    "rows": 8400,
    "missing_paths": 0
  },
  {
    "src": "/content/titanet_medium_extract/manifests/eval_manifest.json",
    "dst": "/content/titanet_medium_extract/manifests_colab/eval_manifest_colab.json",
    "rows": 5000,
    "missing_paths": 0
  }
]
OK: /content/titanet_medium_extract/manifests_colab/train_manifest_colab.json

In [ ]:
SOURCE_TRAIN_MANIFEST = COLAB_MANIFEST_DIR / "train_manifest_colab.json"
TRAIN_FT_MANIFEST = COLAB_MANIFEST_DIR / "train_ft_manifest.json"
VAL_FT_MANIFEST = COLAB_MANIFEST_DIR / "val_ft_manifest.json"

rows = read_jsonl(SOURCE_TRAIN_MANIFEST)
if LIMIT_TRAIN_ROWS and LIMIT_TRAIN_ROWS > 0:
    by_label_tmp = defaultdict(list)
    for r in rows:
        by_label_tmp[str(r["label"])].append(r)
    rng = random.Random(SEED)
    labels_tmp = sorted(by_label_tmp)
    for lab in labels_tmp:
        rng.shuffle(by_label_tmp[lab])
    sampled, exhausted = [], False
    while len(sampled) < LIMIT_TRAIN_ROWS and not exhausted:
        exhausted = True
        for lab in labels_tmp:
            if by_label_tmp[lab] and len(sampled) < LIMIT_TRAIN_ROWS:
                sampled.append(by_label_tmp[lab].pop())
                exhausted = False
    rows = sampled

rows_by_label = defaultdict(list)
for r in rows:
    rows_by_label[str(r["label"])].append(r)

train_rows, val_rows = [], []
rng = random.Random(SEED)
for label, lab_rows in rows_by_label.items():
    rng.shuffle(lab_rows)
    n = len(lab_rows)
    n_val = max(1, int(n * 0.1)) if n >= 10 else (1 if n >= 3 else 0)
    val_rows.extend(lab_rows[:n_val])
    train_rows.extend(lab_rows[n_val:])

if LIMIT_VALID_ROWS and LIMIT_VALID_ROWS > 0:
    val_rows = val_rows[:LIMIT_VALID_ROWS]

write_jsonl(TRAIN_FT_MANIFEST, train_rows)
write_jsonl(VAL_FT_MANIFEST, val_rows)

train_labels = set(str(r["label"]) for r in train_rows)
val_labels = set(str(r["label"]) for r in val_rows)
summary = {
    "source_train_rows_after_limit": len(rows),
    "train_ft_rows": len(train_rows),
    "val_ft_rows": len(val_rows),
    "train_ft_speakers": len(train_labels),
    "val_ft_speakers": len(val_labels),
    "val_labels_not_in_train": len(val_labels - train_labels),
}
print(json.dumps(summary, ensure_ascii=False, indent=2))
(DRIVE_TRAIN_SAVE_DIR / "ft_split_summary.json").write_text(
    json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
)
assert len(val_labels - train_labels) == 0
assert len(train_rows) > 0 and len(val_rows) > 0

{
  "source_train_rows_after_limit": 72000,
  "train_ft_rows": 64800,
  "val_ft_rows": 7200,
  "train_ft_speakers": 900,
  "val_ft_speakers": 900,
  "val_labels_not_in_train": 0
}

In [ ]:
def validate_manifest_audio(manifest_path, sample_count=200):
    rows = read_jsonl(manifest_path, limit=sample_count)
    ok, failed, failed_items = 0, 0, []
    for i, row in enumerate(tqdm(rows, desc=f"validate {Path(manifest_path).name}")):
        audio_path = row.get("audio_filepath")
        label = row.get("label")
        try:
            p = Path(audio_path)
            if not p.exists():
                raise FileNotFoundError(str(p))
            info = sf.info(str(p))
            if info.samplerate != 16000:
                raise ValueError(f"bad sample_rate={info.samplerate}")
            if info.channels != 1:
                raise ValueError(f"bad channels={info.channels}")
            if info.duration <= 0:
                raise ValueError(f"bad duration={info.duration}")
            if label is None or str(label) == "":
                raise ValueError("missing label")
            ok += 1
        except Exception as e:
            failed += 1
            failed_items.append({"index": i, "audio_filepath": audio_path, "label": label, "error": repr(e)})
    report = {"manifest": str(manifest_path), "checked": len(rows), "ok": ok, "failed": failed, "failed_items_sample": failed_items[:20]}
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return report

audio_reports = [validate_manifest_audio(TRAIN_FT_MANIFEST, 200), validate_manifest_audio(VAL_FT_MANIFEST, 200)]
(DRIVE_TRAIN_SAVE_DIR / "manifest_audio_validation_report.json").write_text(
    json.dumps(audio_reports, ensure_ascii=False, indent=2), encoding="utf-8"
)
assert all(r["failed"] == 0 for r in audio_reports)

validate train_ft_manifest.json:   0%|          | 0/200 [00:00<?, ?it/s]

{
  "manifest": "/content/titanet_medium_extract/manifests_colab/train_ft_manifest.json",
  "checked": 200,
  "ok": 200,
  "failed": 0,
  "failed_items_sample": []
}

validate val_ft_manifest.json:   0%|          | 0/200 [00:00<?, ?it/s]

{
  "manifest": "/content/titanet_medium_extract/manifests_colab/val_ft_manifest.json",
  "checked": 200,
  "ok": 200,
  "failed": 0,
  "failed_items_sample": []
}

In [ ]:
def get_train_labels(manifest_path):
    return sorted({str(r["label"]) for r in read_jsonl(manifest_path)})

def replace_last_linear_in_module(module, out_features):
    linear_names = [name for name, child in module.named_modules() if isinstance(child, nn.Linear)]
    if not linear_names:
        return False
    target_name = linear_names[-1]
    parent = module
    parts = target_name.split(".")
    for p in parts[:-1]:
        parent = getattr(parent, p)
    old = getattr(parent, parts[-1])
    new = nn.Linear(old.in_features, out_features, bias=old.bias is not None)
    new.to(device=old.weight.device, dtype=old.weight.dtype)
    setattr(parent, parts[-1], new)
    print(f"Replaced decoder linear: {target_name}, {old.out_features} -> {out_features}")
    return True

def reset_classification_metrics(model, num_classes):
    device = next(model.parameters()).device
    if MulticlassAccuracy is not None:
        for name in ["_macro_accuracy", "_pair_macro_accuracy"]:
            if hasattr(model, name):
                try:
                    setattr(model, name, MulticlassAccuracy(num_classes=num_classes, average="macro").to(device))
                    print(f"Reset metric: {name} -> num_classes={num_classes}")
                except Exception as e:
                    print(f"[WARN] failed to reset {name}: {e}")

def configure_speaker_model_for_finetune(model, train_manifest, val_manifest, labels):
    num_classes = len(labels)
    with open_dict(model.cfg):
        model.cfg.labels = labels
        if "decoder" in model.cfg:
            for k in ["num_classes", "num_classes_total", "n_classes", "num_speakers"]:
                if k in model.cfg.decoder:
                    model.cfg.decoder[k] = num_classes
        if "optim" in model.cfg and model.cfg.optim is not None:
            model.cfg.optim.lr = LEARNING_RATE

    for attr in ["labels", "_labels"]:
        try:
            setattr(model, attr, labels)
        except Exception:
            pass

    replace_last_linear_in_module(model.decoder, num_classes)
    reset_classification_metrics(model, num_classes)

    train_cfg = OmegaConf.create({
        "manifest_filepath": str(train_manifest),
        "sample_rate": 16000,
        "labels": labels,
        "batch_size": BATCH_SIZE,
        "shuffle": True,
        "is_tarred": False,
        "num_workers": NUM_WORKERS,
        "pin_memory": True,
        "min_duration": MIN_AUDIO_DURATION,
        "max_duration": MAX_AUDIO_DURATION,
    })

    val_cfg = OmegaConf.create({
        "manifest_filepath": str(val_manifest),
        "sample_rate": 16000,
        "labels": labels,
        "batch_size": BATCH_SIZE,
        "shuffle": False,
        "is_tarred": False,
        "num_workers": NUM_WORKERS,
        "pin_memory": True,
        "min_duration": MIN_AUDIO_DURATION,
        "max_duration": MAX_AUDIO_DURATION,
    })
    model.setup_training_data(train_cfg)
    model.setup_validation_data(val_cfg)
    return model

def make_trainer(model_run_dir):
    model_run_dir.mkdir(parents=True, exist_ok=True)
    ckpt_cb = ModelCheckpoint(
        dirpath=str(model_run_dir / "checkpoints"),
        filename="{epoch}-{step}-{val_loss:.4f}",
        monitor="val_loss",
        mode="min",
        save_top_k=2,
        save_last=True,
    )
    lr_cb = LearningRateMonitor(logging_interval="step")
    logger = CSVLogger(save_dir=str(model_run_dir), name="logs")
    return pl.Trainer(
        accelerator="gpu" if torch.cuda.is_available() else "cpu",
        devices=1,
        precision=PRECISION if torch.cuda.is_available() else "32-true",
        max_epochs=MAX_EPOCHS,
        limit_train_batches=LIMIT_TRAIN_BATCHES,
        limit_val_batches=LIMIT_VAL_BATCHES,
        num_sanity_val_steps=0,
        log_every_n_steps=10,
        callbacks=[ckpt_cb, lr_cb],
        logger=logger,
        default_root_dir=str(model_run_dir),
        enable_checkpointing=True,
    )

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

labels = get_train_labels(TRAIN_FT_MANIFEST)
print("num train labels:", len(labels), labels[:10])

model = EncDecSpeakerLabelModel.from_pretrained(BASELINE_MODEL_NAME)
print("Loaded:", BASELINE_MODEL_NAME)
print("LightningModule:", isinstance(model, pl.LightningModule))

model = configure_speaker_model_for_finetune(model, TRAIN_FT_MANIFEST, VAL_FT_MANIFEST, labels)

model_run_dir = DRIVE_TRAIN_SAVE_DIR / "titanet_small"
trainer = make_trainer(model_run_dir)

run_config = {
    "run_id": RUN_ID,
    "model_name": BASELINE_MODEL_NAME,
    "dataset": "titanet_local_subset_medium",
    "max_epochs": MAX_EPOCHS,
    "learning_rate": LEARNING_RATE,
    "batch_size": BATCH_SIZE,
    "num_workers": NUM_WORKERS,
    "precision": PRECISION,
    "train_manifest": str(TRAIN_FT_MANIFEST),
    "val_manifest": str(VAL_FT_MANIFEST),
    "num_labels": len(labels),
    "drive_data_dir": str(DRIVE_DATA_DIR),
}
model_run_dir.mkdir(parents=True, exist_ok=True)
(model_run_dir / "run_config.json").write_text(json.dumps(run_config, ensure_ascii=False, indent=2), encoding="utf-8")

print("Start fine-tuning")
print(json.dumps(run_config, ensure_ascii=False, indent=2))
trainer.fit(model)

FINETUNED_NEMO_PATH = model_run_dir / "titanet_small_finetuned_final.nemo"
model.save_to(str(FINETUNED_NEMO_PATH))

(model_run_dir / "labels.json").write_text(json.dumps(labels, ensure_ascii=False, indent=2), encoding="utf-8")
OmegaConf.save(model.cfg, model_run_dir / "model_cfg.yaml")
train_meta = {**run_config, "nemo_path": str(FINETUNED_NEMO_PATH), "model_run_dir": str(model_run_dir)}
(model_run_dir / "train_meta.json").write_text(json.dumps(train_meta, ensure_ascii=False, indent=2), encoding="utf-8")

print("Saved:", FINETUNED_NEMO_PATH)
print("exists:", FINETUNED_NEMO_PATH.exists())
print("size MB:", FINETUNED_NEMO_PATH.stat().st_size / 1024 / 1024)

restored = EncDecSpeakerLabelModel.restore_from(str(FINETUNED_NEMO_PATH))
print("restore OK:", type(restored))
del restored
torch.cuda.empty_cache()
gc.collect()

num train labels: 900 ['0024', '0102', '0210', '0271', '0318', '0329', '0330', '0342', '0343', '0345']
[NeMo I 2026-05-02 07:11:29 cloud:68] Downloading from: https://api.ngc.nvidia.com/v2/models/nvidia/nemo/titanet_small/versions/1.19.0/files/titanet-s.nemo to /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo
[NeMo I 2026-05-02 07:11:30 common:939] Instantiating model from pre-trained checkpoint

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-05-02 07:11:36 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo.
Loaded: titanet_small
LightningModule: True
Replaced decoder linear: final, 16681 -> 900
Reset metric: _macro_accuracy -> num_classes=900
Reset metric: _pair_macro_accuracy -> num_classes=900
[NeMo I 2026-05-02 07:11:37 collections:750] Filtered duration for loading collection is  0.08 hours.
[NeMo I 2026-05-02 07:11:37 collections:751] Dataset successfully loaded with 64789 items and total duration provided from manifest is  35.82 hours.
[NeMo I 2026-05-02 07:11:37 collections:757] # 64789 files loaded accounting to # 900 labels

[NeMo W 2026-05-02 07:11:37 label_models:201] Total number of 900 labels found in all the manifest files.

[NeMo I 2026-05-02 07:11:37 collections:750] Filtered duration for loading collection is  0.08 hours.
[NeMo I 2026-05-02 07:11:37 collections:751] Dataset successfully loaded with 64789 items and total duration provided from manifest is  35.82 hours.
[NeMo I 2026-05-02 07:11:37 collections:757] # 64789 files loaded accounting to # 900 labels
[NeMo I 2026-05-02 07:11:37 collections:750] Filtered duration for loading collection is  0.01 hours.
[NeMo I 2026-05-02 07:11:37 collections:751] Dataset successfully loaded with 7197 items and total duration provided from manifest is  3.96 hours.
[NeMo I 2026-05-02 07:11:37 collections:757] # 7197 files loaded accounting to # 900 labels

INFO:pytorch_lightning.utilities.rank_zero:Using 16bit Automatic Mixed Precision (AMP)
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
INFO:pytorch_lightning.utilities.rank_zero:`Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..

Start fine-tuning
{
  "run_id": "titanet_medium_5epoch_lr5e5_20260502_070940",
  "model_name": "titanet_small",
  "dataset": "titanet_local_subset_medium",
  "max_epochs": 5,
  "learning_rate": 5e-05,
  "batch_size": 16,
  "num_workers": 2,
  "precision": "16-mixed",
  "train_manifest": "/content/titanet_medium_extract/manifests_colab/train_ft_manifest.json",
  "val_manifest": "/content/titanet_medium_extract/manifests_colab/val_ft_manifest.json",
  "num_labels": 900,
  "drive_data_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터"
}

INFO:pytorch_lightning.utilities.rank_zero:You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

[NeMo I 2026-05-02 07:11:39 modelPT:830] Optimizer config = SGD (
    Parameter Group 0
        dampening: 0
        differentiable: False
        foreach: None
        fused: None
        lr: 5e-05
        maximize: False
        momentum: 0.9
        nesterov: False
        weight_decay: 0.0002
    )
[NeMo I 2026-05-02 07:11:39 lr_scheduler:995] Scheduler "<nemo.core.optim.lr_scheduler.CosineAnnealing object at 0x7f989554d460>"
    will be used during training (effective maximum steps = 20250) -
    Parameters :
    (warmup_ratio: 0.1
    min_lr: 0.0
    warmup_steps: null
    max_steps: 20250
    )

INFO:
  | Name                 | Type                              | Params | Mode
-----------------------------------------------------------------------------------
0 | loss                 | AngularSoftmaxLoss                | 0      | train
1 | eval_loss            | AngularSoftmaxLoss                | 0      | train
2 | _accuracy            | TopKClassificationAccuracy        | 0      | train
3 | preprocessor         | AudioToMelSpectrogramPreprocessor | 0      | train
4 | encoder              | ConvASREncoder                    | 4.1 M  | train
5 | decoder              | SpeakerDecoder                    | 2.9 M  | train
6 | _macro_accuracy      | MulticlassAccuracy                | 0      | train
7 | _pair_macro_accuracy | MulticlassAccuracy                | 0      | train
8 | spec_augmentation    | SpectrogramAugmentation           | 0      | train
-----------------------------------------------------------------------------------
7.0 M     Trainable params
0         Non-trainable params
7.0 M     Total params
27.992    Total estimated model params size (MB)
147       Modules in train mode
0         Modules in eval mode
INFO:lightning.pytorch.callbacks.model_summary:
  | Name                 | Type                              | Params | Mode
-----------------------------------------------------------------------------------
0 | loss                 | AngularSoftmaxLoss                | 0      | train
1 | eval_loss            | AngularSoftmaxLoss                | 0      | train
2 | _accuracy            | TopKClassificationAccuracy        | 0      | train
3 | preprocessor         | AudioToMelSpectrogramPreprocessor | 0      | train
4 | encoder              | ConvASREncoder                    | 4.1 M  | train
5 | decoder              | SpeakerDecoder                    | 2.9 M  | train
6 | _macro_accuracy      | MulticlassAccuracy                | 0      | train
7 | _pair_macro_accuracy | MulticlassAccuracy                | 0      | train
8 | spec_augmentation    | SpectrogramAugmentation           | 0      | train
-----------------------------------------------------------------------------------
7.0 M     Trainable params
0         Non-trainable params
7.0 M     Total params
27.992    Total estimated model params size (MB)
147       Modules in train mode
0         Modules in eval mode

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=5` reached.

Saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940/titanet_small/titanet_small_finetuned_final.nemo
exists: True
size MB: 27.12890625

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-05-02 08:25:44 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940/titanet_small/titanet_small_finetuned_final.nemo.
restore OK: <class 'nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel'>

429315

In [ ]:
if not RUN_EVAL_AFTER_TRAIN:
    raise SystemExit("RUN_EVAL_AFTER_TRAIN=False. Training finished.")

def parse_audio_refs(x):
    if pd.isna(x):
        return []
    s = str(x)
    try:
        obj = ast.literal_eval(s)
        if isinstance(obj, list):
            return [str(v) for v in obj]
    except Exception:
        pass
    if ";" in s:
        return [v for v in s.split(";") if v]
    return [s]

def rewrite_audio_refs_field(x):
    return str([rewrite_path_to_colab(v) for v in parse_audio_refs(x)])

def rewrite_trials_to_colab(src, dst):
    df = pd.read_csv(src)
    required = ["verification_audio_ref", "enrollment_audio_refs", "enroll_sec", "label"]
    missing = [c for c in required if c not in df.columns]
    assert not missing, f"Missing trial columns: {missing}"
    df["verification_audio_ref"] = df["verification_audio_ref"].map(rewrite_path_to_colab)
    df["enrollment_audio_refs"] = df["enrollment_audio_refs"].map(rewrite_audio_refs_field)
    df.to_csv(dst, index=False)
    return df

trial_candidates = [MANIFEST_DIR / "trials_local.csv", MANIFEST_DIR / "trials_colab.csv", COLAB_MANIFEST_DIR / "trials_colab.csv"]
trials_src = next((p for p in trial_candidates if p.exists()), None)
assert trials_src is not None, f"No trials file found in {trial_candidates}"

TRIALS_COLAB = COLAB_MANIFEST_DIR / "trials_colab.csv"
trials_df = rewrite_trials_to_colab(trials_src, TRIALS_COLAB)
print("trials rows:", len(trials_df))
print(trials_df.groupby(["enroll_sec", "label"]).size())

df = pd.read_csv(TRIALS_COLAB)
df["enroll_sec"] = df["enroll_sec"].astype(float)
df["label"] = df["label"].astype(int)

if MAX_TRIALS_PER_ENROLL_SEC and MAX_TRIALS_PER_ENROLL_SEC > 0:
    sampled_parts = []
    for enroll_sec, g in df.groupby("enroll_sec"):
        n_total = min(len(g), MAX_TRIALS_PER_ENROLL_SEC)
        label_ratio = g["label"].value_counts(normalize=True).to_dict()
        sub_parts, used = [], 0
        for label_value in sorted(g["label"].unique()):
            gg = g[g["label"] == label_value]
            n = min(int(round(n_total * label_ratio.get(label_value, 0))), len(gg))
            if n > 0:
                sub_parts.append(gg.sample(n=n, random_state=SEED + int(enroll_sec * 10) + label_value))
                used += n
        if used < n_total:
            used_idx = pd.concat(sub_parts).index if sub_parts else []
            rest = g.drop(index=used_idx, errors="ignore")
            if len(rest) > 0:
                sub_parts.append(rest.sample(n=min(n_total-used, len(rest)), random_state=SEED))
        sampled_parts.append(pd.concat(sub_parts))
    eval_trials = pd.concat(sampled_parts).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
else:
    eval_trials = df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)

EVAL_TRIALS_PATH = DRIVE_EVAL_SAVE_DIR / "eval_trials_used.csv"
eval_trials.to_csv(EVAL_TRIALS_PATH, index=False)
print("eval_trials:", len(eval_trials))
print(eval_trials.groupby(["enroll_sec", "label"]).size())

trials rows: 80000
enroll_sec  label
1.5         0        10000
            1         3337
2.0         0        10000
            1         3340
2.5         0        10000
            1         3326
3.0         0        10000
            1         3327
4.0         0        10000
            1         3331
5.0         0        10000
            1         3339
dtype: int64
eval_trials: 80000
enroll_sec  label
1.5         0        10000
            1         3337
2.0         0        10000
            1         3340
2.5         0        10000
            1         3326
3.0         0        10000
            1         3327
4.0         0        10000
            1         3331
5.0         0        10000
            1         3339
dtype: int64

In [ ]:
if "model" in globals():
    del model
torch.cuda.empty_cache()
gc.collect()

def load_baseline():
    m = EncDecSpeakerLabelModel.from_pretrained(BASELINE_MODEL_NAME)
    m.eval()
    m.to(device)
    return m

def load_finetuned():
    m = EncDecSpeakerLabelModel.restore_from(str(FINETUNED_NEMO_PATH))
    m.eval()
    m.to(device)
    return m

baseline_model = load_baseline()
finetuned_model = load_finetuned()

def extract_embedding(model, audio_path):
    audio_path = str(audio_path)
    last_err = None
    if hasattr(model, "get_embedding"):
        try:
            emb = model.get_embedding(audio_path)
            if isinstance(emb, torch.Tensor):
                emb = emb.detach().cpu().float().numpy()
            return np.asarray(emb).squeeze()
        except Exception as e:
            last_err = e
    if hasattr(model, "infer_file"):
        try:
            out = model.infer_file(audio_path)
            if isinstance(out, tuple):
                for item in out:
                    arr = np.asarray(item)
                    if arr.size > 10:
                        return arr.squeeze()
            return np.asarray(out).squeeze()
        except Exception as e:
            last_err = e
    raise RuntimeError(f"Could not extract embedding. path={audio_path}, err={repr(last_err)}")

def normalize_embedding(x):
    x = np.asarray(x, dtype=np.float32).reshape(-1)
    return x / (np.linalg.norm(x) + 1e-12)

def collect_unique_audio_paths(trials):
    paths = set()
    for _, row in trials.iterrows():
        paths.add(rewrite_path_to_colab(row["verification_audio_ref"]))
        for ref in parse_audio_refs(row["enrollment_audio_refs"]):
            paths.add(rewrite_path_to_colab(ref))
    paths = sorted(paths)
    missing = [p for p in paths if not Path(p).exists()]
    if missing:
        print("Missing sample:", missing[:20])
        raise FileNotFoundError(f"Missing {len(missing)} audio files")
    return paths

unique_audio_paths = collect_unique_audio_paths(eval_trials)
print("unique_audio_paths:", len(unique_audio_paths))

def extract_embeddings_for_model(model, model_tag, audio_paths):
    cache, failures = {}, []
    for p in tqdm(audio_paths, desc=f"extract {model_tag}"):
        try:
            emb = extract_embedding(model, p)
            cache[p] = normalize_embedding(emb)
        except Exception as e:
            failures.append({"audio_path": p, "error": repr(e)})
    fail_path = DRIVE_EVAL_SAVE_DIR / f"{model_tag}_embedding_failures.csv"
    pd.DataFrame(failures).to_csv(fail_path, index=False)
    print(model_tag, "success:", len(cache), "failures:", len(failures))
    if not cache:
        raise RuntimeError(f"No embeddings extracted for {model_tag}")
    return cache, failures

baseline_embs, baseline_failures = extract_embeddings_for_model(baseline_model, "baseline", unique_audio_paths)
finetuned_embs, finetuned_failures = extract_embeddings_for_model(finetuned_model, "finetuned_medium_5epoch_lr5e5", unique_audio_paths)

[NeMo I 2026-05-02 08:33:25 cloud:58] Found existing object /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo.
[NeMo I 2026-05-02 08:33:25 cloud:64] Re-using file from: /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo
[NeMo I 2026-05-02 08:33:25 common:939] Instantiating model from pre-trained checkpoint

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-05-02 08:33:30 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo.

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-05-02 08:33:36 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940/titanet_small/titanet_small_finetuned_final.nemo.
unique_audio_paths: 5363

extract baseline:   0%|          | 0/5363 [00:00<?, ?it/s]

baseline success: 5363 failures: 0

extract finetuned_medium_5epoch_lr5e5:   0%|          | 0/5363 [00:00<?, ?it/s]

finetuned_medium_5epoch_lr5e5 success: 5363 failures: 0

In [ ]:
def score_trials(trials, emb_cache):
    rows, skipped = [], 0
    for _, row in tqdm(trials.iterrows(), total=len(trials), desc="score trials"):
        verification_path = rewrite_path_to_colab(row["verification_audio_ref"])
        enroll_paths = [rewrite_path_to_colab(x) for x in parse_audio_refs(row["enrollment_audio_refs"])]
        if verification_path not in emb_cache:
            skipped += 1
            continue
        enroll_vecs = [emb_cache[p] for p in enroll_paths if p in emb_cache]
        if not enroll_vecs:
            skipped += 1
            continue
        enroll_emb = normalize_embedding(np.mean(np.stack(enroll_vecs, axis=0), axis=0))
        ver_emb = emb_cache[verification_path]
        score = float(np.dot(enroll_emb, ver_emb))
        rows.append({
            "trial_id": row.get("trial_id", ""),
            "split": row.get("split", ""),
            "enroll_sec": float(row["enroll_sec"]),
            "label": int(row["label"]),
            "trial_type": row.get("trial_type", ""),
            "score": score,
            "enroll_speaker_id": row.get("enroll_speaker_id", ""),
            "test_speaker_id": row.get("test_speaker_id", ""),
        })
    return pd.DataFrame(rows), skipped

baseline_scores, baseline_skipped = score_trials(eval_trials, baseline_embs)
finetuned_scores, finetuned_skipped = score_trials(eval_trials, finetuned_embs)
baseline_scores["model"] = "baseline"
finetuned_scores["model"] = "finetuned_medium_5epoch_lr5e5"
baseline_scores.to_csv(DRIVE_EVAL_SAVE_DIR / "baseline_trial_scores.csv", index=False)
finetuned_scores.to_csv(DRIVE_EVAL_SAVE_DIR / "finetuned_medium_5epoch_lr5e5_trial_scores.csv", index=False)
print("baseline_scores:", baseline_scores.shape, "skipped:", baseline_skipped)
print("finetuned_scores:", finetuned_scores.shape, "skipped:", finetuned_skipped)

score trials:   0%|          | 0/80000 [00:00<?, ?it/s]

score trials:   0%|          | 0/80000 [00:00<?, ?it/s]

baseline_scores: (80000, 9) skipped: 0
finetuned_scores: (80000, 9) skipped: 0

In [ ]:
def compute_eer(labels, scores):
    labels = np.asarray(labels).astype(int)
    scores = np.asarray(scores).astype(float)
    thresholds = np.unique(scores)
    thresholds = np.concatenate([[scores.max() + 1e-6], thresholds[::-1], [scores.min() - 1e-6]])
    pos = labels == 1
    neg = labels == 0
    n_pos = max(pos.sum(), 1)
    n_neg = max(neg.sum(), 1)
    fars, frrs = [], []
    for th in thresholds:
        pred_pos = scores >= th
        fars.append(np.logical_and(pred_pos, neg).sum() / n_neg)
        frrs.append(np.logical_and(~pred_pos, pos).sum() / n_pos)
    fars = np.asarray(fars)
    frrs = np.asarray(frrs)
    idx = int(np.argmin(np.abs(fars - frrs)))
    return float((fars[idx] + frrs[idx]) / 2.0), float(thresholds[idx])

def tar_at_far(labels, scores, target_far):
    labels = np.asarray(labels).astype(int)
    scores = np.asarray(scores).astype(float)
    thresholds = np.unique(scores)
    thresholds = np.concatenate([[scores.max() + 1e-6], thresholds[::-1], [scores.min() - 1e-6]])
    pos = labels == 1
    neg = labels == 0
    n_pos = max(pos.sum(), 1)
    n_neg = max(neg.sum(), 1)
    best_tar, best_far, best_th = 0.0, 0.0, float(thresholds[0])
    for th in thresholds:
        pred_pos = scores >= th
        far = np.logical_and(pred_pos, neg).sum() / n_neg
        tar = np.logical_and(pred_pos, pos).sum() / n_pos
        if far <= target_far and tar >= best_tar:
            best_tar, best_far, best_th = float(tar), float(far), float(th)
    return best_tar, best_far, best_th

def summarize_scores(df, model_name):
    results = []
    for enroll_sec, g in df.groupby("enroll_sec"):
        y = g["label"].to_numpy()
        s = g["score"].to_numpy()
        eer, eer_th = compute_eer(y, s)
        row = {
            "model": model_name,
            "enroll_sec": float(enroll_sec),
            "n_trials": int(len(g)),
            "n_pos": int((y == 1).sum()),
            "n_neg": int((y == 0).sum()),
            "eer": eer,
            "eer_threshold": eer_th,
            "pos_score_mean": float(s[y == 1].mean()) if (y == 1).any() else None,
            "neg_score_mean": float(s[y == 0].mean()) if (y == 0).any() else None,
        }
        for tfar in TARGET_FARS:
            tar, far, th = tar_at_far(y, s, tfar)
            row[f"tar_at_far_{tfar}"] = tar
            row[f"actual_far_at_far_{tfar}"] = far
            row[f"threshold_at_far_{tfar}"] = th
        results.append(row)
    return pd.DataFrame(results)

baseline_summary = summarize_scores(baseline_scores, "baseline")
finetuned_summary = summarize_scores(finetuned_scores, "finetuned_medium_5epoch_lr5e5")
summary = pd.concat([baseline_summary, finetuned_summary], ignore_index=True)
summary_path = DRIVE_EVAL_SAVE_DIR / "verification_summary_by_enroll_sec.csv"
summary.to_csv(summary_path, index=False)
display(summary)
print("saved:", summary_path)

,model,enroll_sec,n_trials,n_pos,n_neg,eer,eer_threshold,pos_score_mean,neg_score_mean,tar_at_far_0.01,actual_far_at_far_0.01,threshold_at_far_0.01,tar_at_far_0.05,actual_far_at_far_0.05,threshold_at_far_0.05,tar_at_far_0.1,actual_far_at_far_0.1,threshold_at_far_0.1
0,baseline,1.5,13337,3337,10000,0.220879,0.298211,0.396571,0.214730,0.239137,0.01,0.488099,0.473479,0.05,0.405717,0.613126,0.1,0.361377
1,baseline,2.0,13340,3340,10000,0.220979,0.296380,0.395308,0.213193,0.225150,0.01,0.491577,0.460778,0.05,0.409208,0.606587,0.1,0.360951
2,baseline,2.5,13326,3326,10000,0.219792,0.301475,0.403408,0.216840,0.245340,0.01,0.495315,0.484666,0.05,0.412121,0.616657,0.1,0.366612
3,baseline,3.0,13327,3327,10000,0.214654,0.314651,0.416314,0.227214,0.231440,0.01,0.512109,0.491133,0.05,0.422722,0.630598,0.1,0.375993
4,baseline,4.0,13331,3331,10000,0.203221,0.331024,0.438564,0.238183,0.286100,0.01,0.511701,0.549385,0.05,0.427542,0.673972,0.1,0.383656
5,baseline,5.0,13339,3339,10000,0.189939,0.347388,0.455135,0.246949,0.277628,0.01,0.532195,0.527403,0.05,0.447839,0.676550,0.1,0.400087
6,finetuned_medium_5epoch_lr5e5,1.5,13337,3337,10000,0.181300,0.284130,0.475262,0.053444,0.261912,0.01,0.627170,0.534312,0.05,0.494629,0.698232,0.1,0.397241
7,finetuned_medium_5epoch_lr5e5,2.0,13340,3340,10000,0.181718,0.281556,0.475385,0.055415,0.242216,0.01,0.637443,0.542814,0.05,0.491049,0.703293,0.1,0.394126
8,finetuned_medium_5epoch_lr5e5,2.5,13326,3326,10000,0.183402,0.285823,0.481379,0.059759,0.255262,0.01,0.637309,0.552014,0.05,0.496395,0.705352,0.1,0.396275
9,finetuned_medium_5epoch_lr5e5,3.0,13327,3327,10000,0.176117,0.297168,0.495250,0.058495,0.263601,0.01,0.646936,0.546138,0.05,0.512338,0.709047,0.1,0.409399
10,finetuned_medium_5epoch_lr5e5,4.0,13331,3331,10000,0.167209,0.319427,0.518902,0.060374,0.296908,0.01,0.651538,0.591114,0.05,0.512232,0.740919,0.1,0.415328
11,finetuned_medium_5epoch_lr5e5,5.0,13339,3339,10000,0.158365,0.338549,0.532318,0.063802,0.315064,0.01,0.651573,0.598682,0.05,0.521758,0.753220,0.1,0.427634

saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_medium_5epoch_lr5e5_20260502_070940/verification_summary_by_enroll_sec.csv

In [ ]:
comparison_rows = []
for enroll_sec in sorted(summary["enroll_sec"].unique()):
    b = summary[(summary["model"] == "baseline") & (summary["enroll_sec"] == enroll_sec)].iloc[0]
    f = summary[(summary["model"] == "finetuned_medium_5epoch_lr5e5") & (summary["enroll_sec"] == enroll_sec)].iloc[0]
    row = {
        "enroll_sec": float(enroll_sec),
        "baseline_eer": float(b["eer"]),
        "finetuned_medium_5epoch_lr5e5_eer": float(f["eer"]),
        "eer_delta_finetuned_minus_baseline": float(f["eer"] - b["eer"]),
        "eer_improved": bool(f["eer"] < b["eer"]),
        "baseline_pos_score_mean": float(b["pos_score_mean"]),
        "finetuned_pos_score_mean": float(f["pos_score_mean"]),
        "baseline_neg_score_mean": float(b["neg_score_mean"]),
        "finetuned_neg_score_mean": float(f["neg_score_mean"]),
    }
    for tfar in TARGET_FARS:
        col = f"tar_at_far_{tfar}"
        row[f"baseline_{col}"] = float(b[col])
        row[f"finetuned_{col}"] = float(f[col])
        row[f"{col}_delta"] = float(f[col] - b[col])
    comparison_rows.append(row)

comparison = pd.DataFrame(comparison_rows)
comparison_path = DRIVE_EVAL_SAVE_DIR / "baseline_vs_finetuned_medium_5epoch_lr5e5_comparison.csv"
comparison.to_csv(comparison_path, index=False)
display(comparison)
print("saved:", comparison_path)

meta = {
    "train_run_id": RUN_ID,
    "eval_run_id": EVAL_RUN_ID,
    "drive_data_dir": str(DRIVE_DATA_DIR),
    "data_zip_path": str(DATA_ZIP_PATH),
    "finetuned_nemo_path": str(FINETUNED_NEMO_PATH),
    "baseline_model_name": BASELINE_MODEL_NAME,
    "max_epochs": MAX_EPOCHS,
    "learning_rate": LEARNING_RATE,
    "batch_size": BATCH_SIZE,
    "max_trials_per_enroll_sec": MAX_TRIALS_PER_ENROLL_SEC,
    "eval_trials_path": str(EVAL_TRIALS_PATH),
    "n_unique_audio_paths": len(unique_audio_paths),
    "baseline_embedding_failures": len(baseline_failures),
    "finetuned_embedding_failures": len(finetuned_failures),
    "train_save_dir": str(DRIVE_TRAIN_SAVE_DIR),
    "eval_save_dir": str(DRIVE_EVAL_SAVE_DIR),
}
meta_path = DRIVE_EVAL_SAVE_DIR / "eval_meta.json"
meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps(meta, ensure_ascii=False, indent=2))

,enroll_sec,baseline_eer,finetuned_medium_5epoch_lr5e5_eer,eer_delta_finetuned_minus_baseline,eer_improved,baseline_pos_score_mean,finetuned_pos_score_mean,baseline_neg_score_mean,finetuned_neg_score_mean,baseline_tar_at_far_0.01,finetuned_tar_at_far_0.01,tar_at_far_0.01_delta,baseline_tar_at_far_0.05,finetuned_tar_at_far_0.05,tar_at_far_0.05_delta,baseline_tar_at_far_0.1,finetuned_tar_at_far_0.1,tar_at_far_0.1_delta
0,1.5,0.220879,0.181300,-0.039578,True,0.396571,0.475262,0.214730,0.053444,0.239137,0.261912,0.022775,0.473479,0.534312,0.060833,0.613126,0.698232,0.085106
1,2.0,0.220979,0.181718,-0.039261,True,0.395308,0.475385,0.213193,0.055415,0.225150,0.242216,0.017066,0.460778,0.542814,0.082036,0.606587,0.703293,0.096707
2,2.5,0.219792,0.183402,-0.036390,True,0.403408,0.481379,0.216840,0.059759,0.245340,0.255262,0.009922,0.484666,0.552014,0.067348,0.616657,0.705352,0.088695
3,3.0,0.214654,0.176117,-0.038537,True,0.416314,0.495250,0.227214,0.058495,0.231440,0.263601,0.032161,0.491133,0.546138,0.055005,0.630598,0.709047,0.078449
4,4.0,0.203221,0.167209,-0.036013,True,0.438564,0.518902,0.238183,0.060374,0.286100,0.296908,0.010808,0.549385,0.591114,0.041729,0.673972,0.740919,0.066947
5,5.0,0.189939,0.158365,-0.031573,True,0.455135,0.532318,0.246949,0.063802,0.277628,0.315064,0.037436,0.527403,0.598682,0.071279,0.676550,0.753220,0.076670

saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_medium_5epoch_lr5e5_20260502_070940/baseline_vs_finetuned_medium_5epoch_lr5e5_comparison.csv
{
  "train_run_id": "titanet_medium_5epoch_lr5e5_20260502_070940",
  "eval_run_id": "eval_medium_5epoch_lr5e5_20260502_070940",
  "drive_data_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터",
  "data_zip_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_local_subset_medium.zip",
  "finetuned_nemo_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940/titanet_small/titanet_small_finetuned_final.nemo",
  "baseline_model_name": "titanet_small",
  "max_epochs": 5,
  "learning_rate": 5e-05,
  "batch_size": 16,
  "max_trials_per_enroll_sec": 0,
  "eval_trials_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_medium_5epoch_lr5e5_20260502_070940/eval_trials_used.csv",
  "n_unique_audio_paths": 5363,
  "baseline_embedding_failures": 0,
  "finetuned_embedding_failures": 0,
  "train_save_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_medium_5epoch_lr5e5_20260502_070940",
  "eval_save_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_medium_5epoch_lr5e5_20260502_070940"
}