<a href="https://colab.research.google.com/github/Of-Calls/sisicallcall-verification-finetuning/blob/main/titanet_verification_eval_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TitaNet Verification Evaluation Colab v5 — Drive 마운트 경로 고정 버전

이 노트북은 Google Drive API file ID 다운로드를 쓰지 않습니다.

구조:
- Google Drive 전체 마운트
- `MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터` 폴더를 이름 기준으로 찾음
- 그 안의 `titanet_local_subset_small.zip` 사용
- 그 안의 `titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo` 사용
- 결과는 같은 `화자검증 데이터/titanet_eval_runs/{RUN_ID}`에 저장

경로 유니코드 문제를 피하려고, 문자열 전체 경로를 하드코딩하지 않고 폴더명 component를 NFC/NFD 정규화해서 찾습니다.

In [ ]:

# =========================
# 0. Mount Google Drive 전체
# =========================
from google.colab import drive
from pathlib import Path

drive.mount("/content/drive", force_remount=True)

MYDRIVE = Path("/content/drive/MyDrive")
assert MYDRIVE.exists(), "MyDrive mount failed"

print("MYDRIVE:", MYDRIVE)
print("Top-level:")
for p in sorted(MYDRIVE.iterdir()):
    print(" -", p.name)

Mounted at /content/drive
MYDRIVE: /content/drive/MyDrive
Top-level:
 - AI컴퓨터비전 프로젝트
 - ai 스터디
 - github-recovery-codes.txt
 - python_1900_kdy
 - sqld
 - 랭체인 AI 영상객체탐지분석 플랫폼 구축
 - 집중도 체크 프로그램
 - 취업 관련

In [ ]:

# =========================
# 1. Config: 실제 Drive 폴더 구조 기준
# =========================
from pathlib import Path
from datetime import datetime
import unicodedata

# 네 Drive 구조
PROJECT_FOLDER_NAME = "랭체인 AI 영상객체탐지분석 플랫폼 구축"
SERVICE_FOLDER_NAME = "오브콜스(Of-Calls)"
DATA_FOLDER_NAME = "화자검증 데이터"

DATA_ZIP_NAME = "titanet_local_subset_small.zip"

FINETUNE_RUN_NAME = "titanet_20260427_032738"
FINETUNED_NEMO_RELATIVE = Path("titanet_finetune_runs") / FINETUNE_RUN_NAME / "titanet_small" / "titanet_small_finetuned_final.nemo"

BASELINE_MODEL_NAME = "titanet_small"

# 처음엔 enroll_sec별 1000개만 평가. 전체 30000 trial 평가하려면 0.
MAX_TRIALS_PER_ENROLL_SEC = 0

SEED = 42
TARGET_FARS = [0.01, 0.05, 0.10]
RUN_ID = datetime.now().strftime("eval_%Y%m%d_%H%M%S")

print("PROJECT_FOLDER_NAME:", PROJECT_FOLDER_NAME)
print("SERVICE_FOLDER_NAME:", SERVICE_FOLDER_NAME)
print("DATA_FOLDER_NAME:", DATA_FOLDER_NAME)
print("DATA_ZIP_NAME:", DATA_ZIP_NAME)
print("FINETUNED_NEMO_RELATIVE:", FINETUNED_NEMO_RELATIVE)
print("RUN_ID:", RUN_ID)

PROJECT_FOLDER_NAME: 랭체인 AI 영상객체탐지분석 플랫폼 구축
SERVICE_FOLDER_NAME: 오브콜스(Of-Calls)
DATA_FOLDER_NAME: 화자검증 데이터
DATA_ZIP_NAME: titanet_local_subset_small.zip
FINETUNED_NEMO_RELATIVE: titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo
RUN_ID: eval_20260427_053001

In [ ]:

# =========================
# 2. Resolve Drive path by normalized folder names
# =========================
def norm_name(s):
    return unicodedata.normalize("NFC", str(s)).strip()

def find_child_dir(parent: Path, target_name: str) -> Path:
    target = norm_name(target_name)
    children = list(parent.iterdir())

    # exact normalized match
    for child in children:
        if child.is_dir() and norm_name(child.name) == target:
            return child

    # debug output
    print(f"[NOT FOUND] target dir: {target_name}")
    print(f"children of {parent}:")
    for child in children:
        if child.is_dir():
            print(" -", repr(child.name), "normalized:", repr(norm_name(child.name)))
    raise FileNotFoundError(f"Cannot find folder {target_name} under {parent}")

PROJECT_DIR = find_child_dir(MYDRIVE, PROJECT_FOLDER_NAME)
SERVICE_DIR = find_child_dir(PROJECT_DIR, SERVICE_FOLDER_NAME)
DRIVE_DATA_DIR = find_child_dir(SERVICE_DIR, DATA_FOLDER_NAME)

DATA_ZIP_PATH = DRIVE_DATA_DIR / DATA_ZIP_NAME
FINETUNED_NEMO_PATH = DRIVE_DATA_DIR / FINETUNED_NEMO_RELATIVE

EVAL_SAVE_DIR = DRIVE_DATA_DIR / "titanet_eval_runs" / RUN_ID
EVAL_SAVE_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_DIR:", PROJECT_DIR)
print("SERVICE_DIR:", SERVICE_DIR)
print("DRIVE_DATA_DIR:", DRIVE_DATA_DIR)
print("DATA_ZIP_PATH:", DATA_ZIP_PATH)
print("DATA_ZIP exists:", DATA_ZIP_PATH.exists())
print("FINETUNED_NEMO_PATH:", FINETUNED_NEMO_PATH)
print("FINETUNED_NEMO exists:", FINETUNED_NEMO_PATH.exists())
print("EVAL_SAVE_DIR:", EVAL_SAVE_DIR)

print("\nFiles in DRIVE_DATA_DIR:")
for p in sorted(DRIVE_DATA_DIR.iterdir()):
    print(" -", p.name)

assert DATA_ZIP_PATH.exists(), f"Dataset zip not found: {DATA_ZIP_PATH}"
assert FINETUNED_NEMO_PATH.exists(), f"Fine-tuned nemo not found: {FINETUNED_NEMO_PATH}"

PROJECT_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축
SERVICE_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)
DRIVE_DATA_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터
DATA_ZIP_PATH: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_local_subset_small.zip
DATA_ZIP exists: True
FINETUNED_NEMO_PATH: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo
FINETUNED_NEMO exists: True
EVAL_SAVE_DIR: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001

Files in DRIVE_DATA_DIR:
 - titanet_eval_runs
 - titanet_finetune_colab_v3.ipynb
 - titanet_finetune_runs
 - titanet_local_subset_small.zip
 - titanet_verification_eval_colab_v5_drive_mount.ipynb

In [ ]:

# =========================
# 3. Optional install / repair
# =========================
# NeMo / numpy import 에러가 나면 True로 바꾸고 실행 후 런타임 재시작
INSTALL_OR_REPAIR = False

if INSTALL_OR_REPAIR:
    !pip install -q "nemo_toolkit[asr]"
    !pip uninstall -y numpy
    !pip install --no-cache-dir --force-reinstall "numpy==1.26.4"
    print("설치/복구 완료. 런타임 재시작 후 처음부터 다시 실행하세요.")
else:
    print("Skip install/repair.")

Skip install/repair.

In [ ]:

# =========================
# 4. Imports
# =========================
import os
import sys
import json
import ast
import random
import shutil
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import soundfile as sf
from tqdm.auto import tqdm

import lightning.pytorch as pl
from nemo.collections.asr.models import EncDecSpeakerLabelModel

print("python:", sys.version)
print("numpy:", np.__version__)
print("torch:", torch.__version__)
print("cuda:", torch.cuda.is_available())
print("gpu:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)
print("lightning.pytorch:", pl.__version__)

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
numpy: 1.26.4
torch: 2.10.0+cu128
cuda: True
gpu: NVIDIA A100-SXM4-40GB
lightning.pytorch: 2.4.0

In [ ]:

# =========================
# 5. Copy ZIP to /content and extract
# =========================
WORK_ZIP = Path("/content/titanet_local_subset_small.zip")
EXTRACT_ROOT = Path("/content/titanet_eval_extract")

if EXTRACT_ROOT.exists():
    print("Remove old extract root:", EXTRACT_ROOT)
    shutil.rmtree(EXTRACT_ROOT)
EXTRACT_ROOT.mkdir(parents=True, exist_ok=True)

if not WORK_ZIP.exists() or WORK_ZIP.stat().st_size != DATA_ZIP_PATH.stat().st_size:
    print("Copy dataset ZIP to /content ...")
    shutil.copy2(DATA_ZIP_PATH, WORK_ZIP)
else:
    print("Dataset ZIP already copied:", WORK_ZIP)

with zipfile.ZipFile(WORK_ZIP, "r") as zf:
    names = zf.namelist()
    print("ZIP first 30 entries:")
    for n in names[:30]:
        print(" -", n)
    print("Extract to:", EXTRACT_ROOT)
    zf.extractall(EXTRACT_ROOT)

# /content 전체 탐색 금지. EXTRACT_ROOT 내부만 탐색.
candidates = []
if (EXTRACT_ROOT / "manifests").is_dir() and (EXTRACT_ROOT / "wavs").is_dir():
    candidates.append(EXTRACT_ROOT)

for p in EXTRACT_ROOT.rglob("*"):
    if not p.is_dir():
        continue
    try:
        if (p / "manifests").is_dir() and (p / "wavs").is_dir():
            candidates.append(p)
    except OSError:
        continue

candidates = sorted(set(candidates), key=lambda x: len(str(x)))

print("Dataset candidates:")
for c in candidates:
    print(" -", c)

if not candidates:
    print("Extract root children:")
    for p in EXTRACT_ROOT.iterdir():
        print(" -", p)
    raise FileNotFoundError("Could not find dataset dir with manifests/ and wavs/.")

DATA_DIR = candidates[0]
MANIFEST_DIR = DATA_DIR / "manifests"
COLAB_MANIFEST_DIR = DATA_DIR / "manifests_colab"
COLAB_MANIFEST_DIR.mkdir(exist_ok=True)

print("DATA_DIR:", DATA_DIR)
print("MANIFEST_DIR:", MANIFEST_DIR)
print("COLAB_MANIFEST_DIR:", COLAB_MANIFEST_DIR)
print("Manifest files:", [p.name for p in MANIFEST_DIR.iterdir()][:30])

Remove old extract root: /content/titanet_eval_extract
Dataset ZIP already copied: /content/titanet_local_subset_small.zip
ZIP first 30 entries:
 - manifests/
 - manifests/enrollment_manifest_local.csv
 - manifests/eval_manifest.json
 - manifests/evaluation_verification_manifest_local.csv
 - manifests/train_manifest.json
 - manifests/trials_local.csv
 - manifests/valid_manifest.json
 - README_TITANET_LOCAL_SUBSET.md
 - reports/
 - reports/audio_check_report.csv
 - reports/export_summary.json
 - reports/export_titanet_local_subset.log
 - reports/extracted_files.csv
 - reports/failed_extracts.csv
 - wavs/
 - wavs/eval/
 - wavs/eval/0000/
 - wavs/eval/0000/A0002-0000F1012-10120120-00000096_d2a8c8348e.wav
 - wavs/eval/0000/A0009-0000F1012-10120120-00367759_2a12669044.wav
 - wavs/eval/0000/A0010-0000F1012-10120120-00368091_2126cad9a4.wav
 - wavs/eval/0000/A0013-0000F1012-10120120-00368770_e6cd8d4fc3.wav
 - wavs/eval/0000/A0014-0000F1012-10120130-00369282_4b27a49007.wav
 - wavs/eval/0000/A0021-0000F1012-10120140-00372132_2284ff9806.wav
 - wavs/eval/0000/A0026-0000F1012-10120130-00375220_c5f9293d1d.wav
 - wavs/eval/0000/A0040-0000F1012-10120140-04129901_c38768155f.wav
 - wavs/eval/0000/A0048-0000F1012-10120120-00434047_3945c16dea.wav
 - wavs/eval/0000/A0064-0000F1012-10120110-02017972_46267728eb.wav
 - wavs/eval/0000/A0101-0000F1012-10120100-02025741_3d3ea04d60.wav
 - wavs/eval/0000/A0101-0000F1012-10120120-02025717_7fb6ebfeaa.wav
 - wavs/eval/0000/A0124-0000F1012-10120030-02666126_70027f75ee.wav
Extract to: /content/titanet_eval_extract
Dataset candidates:
 - /content/titanet_eval_extract
DATA_DIR: /content/titanet_eval_extract
MANIFEST_DIR: /content/titanet_eval_extract/manifests
COLAB_MANIFEST_DIR: /content/titanet_eval_extract/manifests_colab
Manifest files: ['train_manifest.json', 'enrollment_manifest_local.csv', 'eval_manifest.json', 'valid_manifest.json', 'evaluation_verification_manifest_local.csv', 'trials_local.csv']

In [ ]:

# =========================
# 6. Rewrite trials paths to /content paths
# =========================
LOCAL_ROOT_MARKERS = [
    "D:/aihub_check/titanet_local_subset_small",
    r"D:\aihub_check\titanet_local_subset_small",
]
COLAB_ROOT_STR = str(DATA_DIR).replace("\\", "/")


def rewrite_path_to_colab(path_str):
    if path_str is None:
        return path_str

    s = str(path_str).replace("\\", "/")

    for marker in LOCAL_ROOT_MARKERS:
        m = marker.replace("\\", "/")
        if s.startswith(m):
            return s.replace(m, COLAB_ROOT_STR, 1)

    if s.startswith("/content/"):
        return s

    idx = s.find("/wavs/")
    if idx >= 0:
        return COLAB_ROOT_STR + s[idx:]

    return s


def parse_audio_refs(x):
    if pd.isna(x):
        return []
    s = str(x)
    try:
        obj = ast.literal_eval(s)
        if isinstance(obj, list):
            return [str(v) for v in obj]
    except Exception:
        pass
    if ";" in s:
        return [v for v in s.split(";") if v]
    return [s]


def rewrite_audio_refs_field(x):
    refs = parse_audio_refs(x)
    return str([rewrite_path_to_colab(v) for v in refs])


def rewrite_trials_to_colab(src, dst):
    df = pd.read_csv(src)
    required = ["verification_audio_ref", "enrollment_audio_refs", "enroll_sec", "label"]
    missing = [c for c in required if c not in df.columns]
    assert not missing, f"Missing trial columns: {missing}"

    df["verification_audio_ref"] = df["verification_audio_ref"].map(rewrite_path_to_colab)
    df["enrollment_audio_refs"] = df["enrollment_audio_refs"].map(rewrite_audio_refs_field)
    df.to_csv(dst, index=False)
    return df

trial_candidates = [
    MANIFEST_DIR / "trials_local.csv",
    MANIFEST_DIR / "trials_colab.csv",
    COLAB_MANIFEST_DIR / "trials_colab.csv",
]

trials_src = None
for p in trial_candidates:
    if p.exists():
        trials_src = p
        break

assert trials_src is not None, f"No trials file found in {trial_candidates}"

TRIALS_COLAB = COLAB_MANIFEST_DIR / "trials_colab.csv"
trials_df = rewrite_trials_to_colab(trials_src, TRIALS_COLAB)

print("trials_src:", trials_src)
print("TRIALS_COLAB:", TRIALS_COLAB)
print("trials rows:", len(trials_df))
print(trials_df.groupby(["enroll_sec", "label"]).size())

trials_src: /content/titanet_eval_extract/manifests/trials_local.csv
TRIALS_COLAB: /content/titanet_eval_extract/manifests_colab/trials_colab.csv
trials rows: 30000
enroll_sec  label
1.0         0        5687
            1        1900
2.0         0        5608
            1        1868
3.0         0        5577
            1        1857
5.0         0        5628
            1        1875
dtype: int64

In [ ]:

# =========================
# 7. Sample trials
# =========================
df = pd.read_csv(TRIALS_COLAB)
df["enroll_sec"] = df["enroll_sec"].astype(float)
df["label"] = df["label"].astype(int)

if MAX_TRIALS_PER_ENROLL_SEC and MAX_TRIALS_PER_ENROLL_SEC > 0:
    sampled_parts = []

    for enroll_sec, g in df.groupby("enroll_sec"):
        n_total = min(len(g), MAX_TRIALS_PER_ENROLL_SEC)
        label_ratio = g["label"].value_counts(normalize=True).to_dict()
        sub_parts = []
        used = 0

        for label_value in sorted(g["label"].unique()):
            gg = g[g["label"] == label_value]
            n = int(round(n_total * label_ratio.get(label_value, 0)))
            n = min(n, len(gg))
            if n > 0:
                sub_parts.append(gg.sample(n=n, random_state=SEED + int(enroll_sec * 10) + label_value))
                used += n

        if used < n_total:
            used_idx = pd.concat(sub_parts).index if sub_parts else []
            rest = g.drop(index=used_idx, errors="ignore")
            if len(rest) > 0:
                sub_parts.append(rest.sample(n=min(n_total - used, len(rest)), random_state=SEED))

        sampled_parts.append(pd.concat(sub_parts))

    eval_trials = pd.concat(sampled_parts).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
else:
    eval_trials = df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)

EVAL_TRIALS_PATH = EVAL_SAVE_DIR / "eval_trials_used.csv"
eval_trials.to_csv(EVAL_TRIALS_PATH, index=False)

print("eval_trials:", len(eval_trials))
print(eval_trials.groupby(["enroll_sec", "label"]).size())
print("saved:", EVAL_TRIALS_PATH)

eval_trials: 30000
enroll_sec  label
1.0         0        5687
            1        1900
2.0         0        5608
            1        1868
3.0         0        5577
            1        1857
5.0         0        5628
            1        1875
dtype: int64
saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/eval_trials_used.csv

In [ ]:

# =========================
# 8. Load baseline / fine-tuned models
# =========================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def load_baseline():
    model = EncDecSpeakerLabelModel.from_pretrained(BASELINE_MODEL_NAME)
    model.eval()
    model.to(device)
    return model

def load_finetuned():
    model = EncDecSpeakerLabelModel.restore_from(str(FINETUNED_NEMO_PATH))
    model.eval()
    model.to(device)
    return model

baseline_model = load_baseline()
finetuned_model = load_finetuned()

print("baseline loaded:", type(baseline_model))
print("finetuned loaded:", type(finetuned_model))
print("FINETUNED_NEMO_PATH:", FINETUNED_NEMO_PATH)

[NeMo I 2026-04-27 05:30:27 cloud:58] Found existing object /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo.
[NeMo I 2026-04-27 05:30:27 cloud:64] Re-using file from: /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo
[NeMo I 2026-04-27 05:30:27 common:939] Instantiating model from pre-trained checkpoint

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-04-27 05:30:32 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /root/.cache/torch/NeMo/NeMo_2.7.3/titanet-s/908e9576cf7dd7420e75f73ceb0b72e1/titanet-s.nemo.

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
    - id07182
    - id07183
    - id07185
    - id07186
    - id07187
    - id07188
    - id07189
    - id07191
    - id07192
    - id07194
    - id07195
    - id07196
    - id07197
    - id07198
    - id07199
    - id07200
    - id07202
    - id07204
    - id07205
    - id07206
    - id07207
    - id07208
    - id07209
    - id07210
    - id07212
    - id07213
    - id07214
    - id07215
    - id07217
    - id07218
    - id07219
    - id07220
    - id07221
    - id07223
    - id07227
    - id07228
    - id07229
    - id07230
    - id07232
    - id07233
    - id07234
    - id07235
    - id07236
    - id07238
    - id07240
    - id07241
    - id07242
    - id07243
    - id07244
    - id07246
    - id07247
    - id07250
    - id07251
    - id07253
    - id07254
    - id07255
    - id07256
    - id07258
    - id07259
    - id07262
    - id07263
    - id07264
    - id07265
    - id07268
    - id07269
    - id07272
    - id07273
    - id07275
    - id07276
    - id07277
    - id07278
    - id07279
    - id07283
    - id07284
    - id07285
    - id07288
    - id07290
    - id07292
    - id07293
    - id07294
    - id07295
    - id07296
    - id07297
    - id07299
    - id07303
    - id07305
    - id07306
    - id07308
    - id07311
    - id07314
    - id07316
    - id07320
    - id07321
    - id07322
    - id07332
    - id07333
    - id07334
    - id07335
    - id07337
    - id07338
    - id07341
    - id07342
    - id07343
    - id07344
    - id07345
    - id07346
    - id07349
    - id07350
    - id07351
    - id07352
    - id07353
    - id07355
    - id07356
    - id07357
    - id07358
    - id07359
    - id07360
    - id07361
    - id07362
    - id07363
    - id07366
    - id07367
    - id07368
    - id07369
    - id07370
    - id07371
    - id07374
    - id07375
    - id07376
    - id07377
    - id07383
    - id07384
    - id07385
    - id07388
    - id07389
    - id07392
    - id07393
    - id07394
    - id07395
    - id07397
    - id07398
    - id07399
    - id07400
    - id07401
    - id07402
    - id07403
    - id07404
    - id07405
    - id07407
    - id07408
    - id07409
    - id07411
    - id07412
    - id07413
    - id07415
    - id07416
    - id07417
    - id07418
    - id07419
    - id07421
    - id07422
    - id07423
    - id07427
    - id07428
    - id07429
    - id07430
    - id07431
    - id07432
    - id07433
    - id07434
    - id07437
    - id07438
    - id07439
    - id07441
    - id07442
    - id07445
    - id07446
    - id07447
    - id07448
    - id07452
    - id07453
    - id07454
    - id07455
    - id07456
    - id07457
    - id07459
    - id07460
    - id07461
    - id07462
    - id07463
    - id07465
    - id07466
    - id07468
    - id07469
    - id07470
    - id07471
    - id07473
    - id07474
    - id07477
    - id07478
    - id07483
    - id07484
    - id07489
    - id07491
    - id07492
    - id07493
    - id07495
    - id07496
    - id07497
    - id07498
    - id07500
    - id07502
    - id07506
    - id07507
    - id07508
    - id07510
    - id07511
    - id07512
    - id07517
    - id07519
    - id07520
    - id07522
    - id07524
    - id07525
    - id07526
    - id07527
    - id07528
    - id07529
    - id07531
    - id07532
    - id07533
    - id07534
    - id07535
    - id07536
    - id07537
    - id07538
    - id07539
    - id07540
    - id07541
    - id07543
    - id07545
    - id07546
    - id07547
    - id07548
    - id07549
    - id07550
    - id07551
    - id07552
    - id07553
    - id07554
    - id07555
    - id07556
    - id07558
    - id07560
    - id07561
    - id07562
    - id07564
    - id07565
    - id07566
    - id07567
    - id07568
    - id07569
    - id07570
    - id07571
    - id07572
    - id07574
    - id07575
    - id07576
    - id07577
    - id07578
    - id07579
    - id07580
    - id07581
    - id07582
    - id07583
    - id07585
    - id07586
    - id07587
    - id07588
    - id07589
    - id07590
    - id07591
    - id07592
    - id07593
    - id07598
    - id07599
    - id07600
    - id07611
    - id07612
    - id07613
    - id07614
    - id07615
    - id07616
    - id07617
    - id07618
    - id07622
    - id07623
    - id07624
    - id07625
    - id07626
    - id07627
    - id07628
    - id07630
    - id07631
    - id07635
    - id07636
    - id07637
    - id07638
    - id07639
    - id07640
    - id07641
    - id07642
    - id07643
    - id07644
    - id07646
    - id07647
    - id07648
    - id07649
    - id07652
    - id07656
    - id07658
    - id07660
    - id07661
    - id07662
    - id07664
    - id07666
    - id07669
    - id07670
    - id07671
    - id07672
    - id07673
    - id07675
    - id07678
    - id07679
    - id07680
    - id07681
    - id07682
    - id07683
    - id07685
    - id07686
    - id07688
    - id07689
    - id07691
    - id07692
    - id07693
    - id07694
    - id07695
    - id07696
    - id07697
    - id07700
    - id07701
    - id07702
    - id07703
    - id07704
    - id07705
    - id07706
    - id07707
    - id07708
    - id07711
    - id07713
    - id07714
    - id07715
    - id07716
    - id07717
    - id07719
    - id07720
    - id07721
    - id07723
    - id07724
    - id07725
    - id07726
    - id07727
    - id07728
    - id07730
    - id07732
    - id07733
    - id07734
    - id07735
    - id07736
    - id07737
    - id07738
    - id07739
    - id07740
    - id07741
    - id07742
    - id07744
    - id07745
    - id07747
    - id07748
    - id07749
    - id07750
    - id07751
    - id07752
    - id07753
    - id07755
    - id07756
    - id07758
    - id07759
    - id07760
    - id07761
    - id07764
    - id07768
    - id07769
    - id07770
    - id07771
    - id07773
    - id07774
    - id07775
    - id07776
    - id07780
    - id07783
    - id07785
    - id07786
    - id07798
    - id07799
    - id07800
    - id07801
    - id07803
    - id07805
    - id07807
    - id07809
    - id07811
    - id07812
    - id07814
    - id07816
    - id07818
    - id07819
    - id07820
    - id07824
    - id07825
    - id07826
    - id07827
    - id07828
    - id07829
    - id07831
    - id07832
    - id07833
    - id07834
    - id07835
    - id07837
    - id07838
    - id07839
    - id07840
    - id07841
    - id07844
    - id07845
    - id07846
    - id07847
    - id07848
    - id07849
    - id07850
    - id07851
    - id07852
    - id07853
    - id07856
    - id07857
    - id07858
    - id07860
    - id07861
    - id07862
    - id07863
    - id07864
    - id07866
    - id07869
    - id07870
    - id07875
    - id07876
    - id07882
    - id07883
    - id07884
    - id07885
    - id07886
    - id07887
    - id07894
    - id07895
    - id07898
    - id07901
    - id07902
    - id07910
    - id07911
    - id07912
    - id07914
    - id07916
    - id07917
    - id07926
    - id07927
    - id07928
    - id07941
    - id07943
    - id07944
    - id07947
    - id07948
    - id07949
    - id07950
    - id07951
    - id07953
    - id07954
    - id07955
    - id07956
    - id07957
    - id07958
    - id07959
    - id07960
    - id07962
    - id07963
    - id07964
    - id07967
    - id07968
    - id07970
    - id07971
    - id07972
    - id07973
    - id07974
    - id07975
    - id07976
    - id07977
    - id07978
    - id07979
    - id07980
    - id07981
    - id07982
    - id07983
    - id07984
    - id07985
    - id07987
    - id07988
    - id07989
    - id07990
    - id07991
    - id07992
    - id07993
    - id07995
    - id07996
    - id07997
    - id07998
    - id07999
    - id08000
    - id08001
    - id08002
    - id08003
    - id08012
    - id08013
    - id08014
    - id08015
    - id08016
    - id08018
    - id08019
    - id08020
    - id08022
    - id08023
    - id08024
    - id08025
    - id08026
    - id08027
    - id08028
    - id08029
    - id08030
    - id08037
    - id08039
    - id08040
    - id08041
    - id08042
    - id08043
    - id08044
    - id08046
    - id08047
    - id08048
    - id08049
    - id08052
    - id08053
    - id08054
    - id08064
    - id08065
    - id08066
    - id08067
    - id08068
    - id08071
    - id08073
    - id08074
    - id08078
    - id08079
    - id08080
    - id08081
    - id08086
    - id08088
    - id08089
    - id08093
    - id08094
    - id08095
    - id08096
    - id08097
    - id08098
    - id08099
    - id08106
    - id08108
    - id08110
    - id08113
    - id08114
    - id08115
    - id08119
    - id08120
    - id08121
    - id08122
    - id08123
    - id08124
    - id08125
    - id08126
    - id08127
    - id08128
    - id08129
    - id08130
    - id08132
    - id08134
    - id08137
    - id08138
    - id08139
    - id08142
    - id08143
    - id08144
    - id08145
    - id08146
    - id08147
    - id08148
    - id08154
    - id08155
    - id08158
    - id08159
    - id08160
    - id08162
    - id08163
    - id08165
    - id08166
    - id08167
    - id08169
    - id08170
    - id08171
    - id08172
    - id08173
    - id08175
    - id08176
    - id08178
    - id08179
    - id08180
    - id08183
    - id08184
    - id08185
    - id08186
    - id08187
    - id08188
    - id08190
    - id08191
    - id08192
    - id08193
    - id08194
    - id08195
    - id08198
    - id08200
    - id08201
    - id08202
    - id08203
    - id08204
    - id08206
    - id08209
    - id08210
    - id08211
    - id08212
    - id08213
    - id08215
    - id08217
    - id08218
    - id08219
    - id08220
    - id08221
    - id08222
    - id08230
    - id08231
    - id08232
    - id08234
    - id08235
    - id08236
    - id08238
    - id08239
    - id08240
    - id08241
    - id08242
    - id08243
    - id08244
    - id08245
    - id08246
    - id08247
    - id08249
    - id08250
    - id08251
    - id08253
    - id08258
    - id08259
    - id08260
    - id08261
    - id08263
    - id08264
    - id08266
    - id08267
    - id08271
    - id08273
    - id08274
    - id08277
    - id08278
    - id08279
    - id08280
    - id08281
    - id08282
    - id08283
    - id08284
    - id08285
    - id08286
    - id08287
    - id08288
    - id08289
    - id08290
    - id08291
    - id08292
    - id08293
    - id08294
    - id08295
    - id08297
    - id08298
    - id08299
    - id08300
    - id08302
    - id08303
    - id08305
    - id08306
    - id08307
    - id08309
    - id08311
    - id08312
    - id08313
    - id08314
    - id08315
    - id08317
    - id08318
    - id08320
    - id08321
    - id08323
    - id08324
    - id08327
    - id08329
    - id08330
    - id08331
    - id08333
    - id08334
    - id08335
    - id08337
    - id08338
    - id08339
    - id08340
    - id08343
    - id08344
    - id08347
    - id08348
    - id08349
    - id08350
    - id08351
    - id08352
    - id08353
    - id08354
    - id08355
    - id08356
    - id08358
    - id08360
    - id08362
    - id08364
    - id08365
    - id08368
    - id08370
    - id08372
    - id08373
    - id08375
    - id08376
    - id08377
    - id08380
    - id08381
    - id08382
    - id08394
    - id08395
    - id08396
    - id08397
    - id08398
    - id08399
    - id08400
    - id08402
    - id08403
    - id08404
    - id08405
    - id08406
    - id08408
    - id08411
    - id08414
    - id08415
    - id08416
    - id08417
    - id08418
    - id08419
    - id08420
    - id08421
    - id08422
    - id08423
    - id08424
    - id08426
    - id08432
    - id08433
    - id08434
    - id08437
    - id08438
    - id08440
    - id08441
    - id08442
    - id08443
    - id08445
    - id08446
    - id08451
    - id08453
    - id08454
    - id08455
    - id08457
    - id08458
    - id08459
    - id08462
    - id08463
    - id08464
    - id08465
    - id08467
    - id08468
    - id08470
    - id08471
    - id08472
    - id08474
    - id08475
    - id08476
    - id08477
    - id08478
    - id08480
    - id08481
    - id08482
    - id08483
    - id08489
    - id08490
    - id08492
    - id08494
    - id08496
    - id08497
    - id08498
    - id08499
    - id08500
    - id08501
    - id08502
    - id08510
    - id08511
    - id08512
    - id08513
    - id08515
    - id08516
    - id08517
    - id08518
    - id08520
    - id08521
    - id08522
    - id08523
    - id08524
    - id08525
    - id08527
    - id08528
    - id08529
    - id08530
    - id08531
    - id08532
    - id08533
    - id08534
    - id08535
    - id08536
    - id08538
    - id08540
    - id08543
    - id08544
    - id08545
    - id08546
    - id08547
    - id08549
    - id08551
    - id08553
    - id08554
    - id08555
    - id08556
    - id08563
    - id08564
    - id08565
    - id08566
    - id08567
    - id08568
    - id08569
    - id08570
    - id08572
    - id08573
    - id08574
    - id08577
    - id08578
    - id08580
    - id08581
    - id08583
    - id08584
    - id08585
    - id08586
    - id08587
    - id08588
    - id08589
    - id08590
    - id08592
    - id08593
    - id08595
    - id08597
    - id08598
    - id08599
    - id08600
    - id08601
    - id08602
    - id08603
    - id08604
    - id08605
    - id08606
    - id08607
    - id08608
    - id08609
    - id08610
    - id08611
    - id08612
    - id08613
    - id08614
    - id08615
    - id08616
    - id08617
    - id08618
    - id08622
    - id08623
    - id08624
    - id08625
    - id08626
    - id08627
    - id08628
    - id08629
    - id08633
    - id08634
    - id08635
    - id08637
    - id08638
    - id08639
    - id08640
    - id08641
    - id08642
    - id08643
    - id08645
    - id08646
    - id08647
    - id08648
    - id08649
    - id08650
    - id08651
    - id08652
    - id08653
    - id08655
    - id08656
    - id08657
    - id08658
    - id08659
    - id08660
    - id08661
    - id08663
    - id08665
    - id08666
    - id08667
    - id08668
    - id08669
    - id08670
    - id08671
    - id08672
    - id08674
    - id08676
    - id08677
    - id08678
    - id08679
    - id08680
    - id08681
    - id08683
    - id08684
    - id08685
    - id08686
    - id08687
    - id08688
    - id08689
    - id08691
    - id08692
    - id08693
    - id08694
    - id08695
    - id08698
    - id08699
    - id08700
    - id08702
    - id08703
    - id08704
    - id08705
    - id08706
    - id08707
    - id08708
    - id08709
    - id08710
    - id08711
    - id08713
    - id08714
    - id08715
    - id08716
    - id08719
    - id08721
    - id08722
    - id08723
    - id08724
    - id08725
    - id08726
    - id08727
    - id08728
    - id08730
    - id08731
    - id08732
    - id08733
    - id08736
    - id08737
    - id08738
    - id08739
    - id08740
    - id08741
    - id08742
    - id08743
    - id08745
    - id08746
    - id08747
    - id08748
    - id08749
    - id08750
    - id08751
    - id08754
    - id08755
    - id08756
    - id08757
    - id08758
    - id08760
    - id08761
    - id08762
    - id08764
    - id08765
    - id08766
    - id08768
    - id08769
    - id08771
    - id08773
    - id08774
    - id08775
    - id08776
    - id08781
    - id08782
    - id08783
    - id08784
    - id08785
    - id08786
    - id08788
    - id08789
    - id08790
    - id08792
    - id08794
    - id08795
    - id08797
    - id08799
    - id08800
    - id08801
    - id08802
    - id08803
    - id08804
    - id08805
    - id08806
    - id08808
    - id08809
    - id08810
    - id08811
    - id08819
    - id08820
    - id08821
    - id08822
    - id08823
    - id08826
    - id08830
    - id08831
    - id08832
    - id08834
    - id08837
    - id08839
    - id08840
    - id08850
    - id08853
    - id08860
    - id08862
    - id08863
    - id08864
    - id08866
    - id08868
    - id08870
    - id08871
    - id08872
    - id08873
    - id08875
    - id08876
    - id08877
    - id08878
    - id08879
    - id08881
    - id08882
    - id08883
    - id08884
    - id08885
    - id08887
    - id08890
    - id08891
    - id08892
    - id08896
    - id08898
    - id08900
    - id08901
    - id08902
    - id08903
    - id08904
    - id08906
    - id08907
    - id08909
    - id08910
    - id08912
    - id08913
    - id08915
    - id08916
    - id08917
    - id08919
    - id08920
    - id08923
    - id08925
    - id08926
    - id08927
    - id08928
    - id08929
    - id08930
    - id08931
    - id08933
    - id08936
    - id08937
    - id08938
    - id08940
    - id08941
    - id08942
    - id08944
    - id08945
    - id08950
    - id08953
    - id08954
    - id08955
    - id08967
    - id08968
    - id08969
    - id08971
    - id08972
    - id08973
    - id08974
    - id08975
    - id08976
    - id08977
    - id08980
    - id08981
    - id08982
    - id08983
    - id08984
    - id08992
    - id08993
    - id08994
    - id08996
    - id08997
    - id08998
    - id08999
    - id09000
    - id09003
    - id09004
    - id09005
    - id09006
    - id09007
    - id09008
    - id09009
    - id09010
    - id09012
    - id09013
    - id09015
    - id09016
    - id09018
    - id09020
    - id09021
    - id09022
    - id09023
    - id09024
    - id09025
    - id09027
    - id09028
    - id09029
    - id09030
    - id09031
    - id09032
    - id09033
    - id09034
    - id09035
    - id09036
    - id09038
    - id09039
    - id09040
    - id09044
    - id09046
    - id09047
    - id09048
    - id09049
    - id09051
    - id09052
    - id09053
    - id09054
    - id09055
    - id09056
    - id09057
    - id09059
    - id09061
    - id09062
    - id09063
    - id09064
    - id09065
    - id09066
    - id09067
    - id09068
    - id09069
    - id09070
    - id09071
    - id09074
    - id09075
    - id09076
    - id09078
    - id09079
    - id09081
    - id09082
    - id09083
    - id09087
    - id09088
    - id09091
    - id09092
    - id09094
    - id09095
    - id09098
    - id09099
    - id09100
    - id09108
    - id09109
    - id09110
    - id09111
    - id09112
    - id09116
    - id09119
    - id09121
    - id09123
    - id09124
    - id09125
    - id09138
    - id09139
    - id09143
    - id09144
    - id09145
    - id09146
    - id09147
    - id09149
    - id09152
    - id09153
    - id09154
    - id09155
    - id09156
    - id09159
    - id09160
    - id09161
    - id09162
    - id09163
    - id09164
    - id09171
    - id09172
    - id09174
    - id09175
    - id09179
    - id09181
    - id09185
    - id09186
    - id09187
    - id09188
    - id09189
    - id09190
    - id09192
    - id09193
    - id09194
    - id09197
    - id09198
    - id09199
    - id09200
    - id09201
    - id09202
    - id09203
    - id09204
    - id09205
    - id09207
    - id09210
    - id09211
    - id09212
    - id09213
    - id09214
    - id09215
    - id09216
    - id09217
    - id09218
    - id09220
    - id09222
    - id09224
    - id09225
    - id09226
    - id09227
    - id09229
    - id09230
    - id09231
    - id09232
    - id09234
    - id09235
    - id09236
    - id09237
    - id09238
    - id09240
    - id09242
    - id09243
    - id09245
    - id09252
    - id09255
    - id09262
    - id09263
    - id09268
    - id09269
    - id09271
    - id09272
    - id10001
    - id10002
    - id10003
    - id10004
    - id10005
    - id10006
    - id10007
    - id10008
    - id10009
    - id10010
    - id10011
    - id10012
    - id10013
    - id10014
    - id10015
    - id10016
    - id10017
    - id10018
    - id10019
    - id10020
    - id10021
    - id10022
    - id10023
    - id10024
    - id10025
    - id10026
    - id10027
    - id10028
    - id10029
    - id10030
    - id10031
    - id10032
    - id10033
    - id10034
    - id10035
    - id10036
    - id10037
    - id10038
    - id10039
    - id10040
    - id10041
    - id10042
    - id10043
    - id10044
    - id10045
    - id10046
    - id10047
    - id10048
    - id10049
    - id10050
    - id10051
    - id10052
    - id10053
    - id10054
    - id10055
    - id10056
    - id10057
    - id10058
    - id10059
    - id10060
    - id10061
    - id10062
    - id10063
    - id10064
    - id10065
    - id10066
    - id10067
    - id10068
    - id10069
    - id10070

[NeMo I 2026-04-27 05:30:38 save_restore_connector:285] Model EncDecSpeakerLabelModel was successfully restored from /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo.
baseline loaded: <class 'nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel'>
finetuned loaded: <class 'nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel'>
FINETUNED_NEMO_PATH: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo

In [ ]:

# =========================
# 9. Embedding helpers
# =========================
def extract_embedding(model, audio_path):
    audio_path = str(audio_path)
    last_err = None

    if hasattr(model, "get_embedding"):
        try:
            emb = model.get_embedding(audio_path)
            if isinstance(emb, torch.Tensor):
                emb = emb.detach().cpu().float().numpy()
            return np.asarray(emb).squeeze()
        except Exception as e:
            last_err = e

    if hasattr(model, "infer_file"):
        try:
            out = model.infer_file(audio_path)
            if isinstance(out, tuple):
                for item in out:
                    arr = np.asarray(item)
                    if arr.size > 10:
                        return arr.squeeze()
            return np.asarray(out).squeeze()
        except Exception as e:
            last_err = e

    raise RuntimeError(f"Could not extract embedding. path={audio_path}, err={repr(last_err)}")


def normalize_embedding(x):
    x = np.asarray(x, dtype=np.float32).reshape(-1)
    return x / (np.linalg.norm(x) + 1e-12)


def collect_unique_audio_paths(trials):
    paths = set()
    for _, row in trials.iterrows():
        paths.add(rewrite_path_to_colab(row["verification_audio_ref"]))
        for ref in parse_audio_refs(row["enrollment_audio_refs"]):
            paths.add(rewrite_path_to_colab(ref))

    paths = sorted(paths)
    missing = [p for p in paths if not Path(p).exists()]
    if missing:
        print("Missing sample:")
        for p in missing[:20]:
            print(p)
        raise FileNotFoundError(f"Missing {len(missing)} audio files")

    return paths

unique_audio_paths = collect_unique_audio_paths(eval_trials)
print("unique_audio_paths:", len(unique_audio_paths))
print(unique_audio_paths[:3])

unique_audio_paths: 3221
['/content/titanet_eval_extract/wavs/eval/0000/A0002-0000F1012-10120120-00000096_d2a8c8348e.wav', '/content/titanet_eval_extract/wavs/eval/0000/A0009-0000F1012-10120120-00367759_2a12669044.wav', '/content/titanet_eval_extract/wavs/eval/0000/A0010-0000F1012-10120120-00368091_2126cad9a4.wav']

In [ ]:

# =========================
# 10. Extract embeddings
# =========================
def extract_embeddings_for_model(model, model_tag, audio_paths):
    cache = {}
    failures = []

    for p in tqdm(audio_paths, desc=f"extract {model_tag}"):
        try:
            emb = extract_embedding(model, p)
            cache[p] = normalize_embedding(emb)
        except Exception as e:
            failures.append({"audio_path": p, "error": repr(e)})

    fail_path = EVAL_SAVE_DIR / f"{model_tag}_embedding_failures.csv"
    pd.DataFrame(failures).to_csv(fail_path, index=False)

    print(model_tag, "success:", len(cache), "failures:", len(failures), "fail_path:", fail_path)

    if not cache:
        raise RuntimeError(f"No embeddings extracted for {model_tag}")

    return cache, failures

baseline_embs, baseline_failures = extract_embeddings_for_model(baseline_model, "baseline", unique_audio_paths)
finetuned_embs, finetuned_failures = extract_embeddings_for_model(finetuned_model, "finetuned", unique_audio_paths)

extract baseline:   0%|          | 0/3221 [00:00<?, ?it/s]

baseline success: 3221 failures: 0 fail_path: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/baseline_embedding_failures.csv

extract finetuned:   0%|          | 0/3221 [00:00<?, ?it/s]

finetuned success: 3221 failures: 0 fail_path: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/finetuned_embedding_failures.csv

In [ ]:

# =========================
# 11. Score trials
# =========================
def score_trials(trials, emb_cache):
    rows = []
    skipped = 0

    for _, row in tqdm(trials.iterrows(), total=len(trials), desc="score trials"):
        verification_path = rewrite_path_to_colab(row["verification_audio_ref"])
        enroll_paths = [rewrite_path_to_colab(x) for x in parse_audio_refs(row["enrollment_audio_refs"])]

        if verification_path not in emb_cache:
            skipped += 1
            continue

        enroll_vecs = [emb_cache[p] for p in enroll_paths if p in emb_cache]
        if not enroll_vecs:
            skipped += 1
            continue

        enroll_emb = normalize_embedding(np.mean(np.stack(enroll_vecs, axis=0), axis=0))
        ver_emb = emb_cache[verification_path]
        score = float(np.dot(enroll_emb, ver_emb))

        rows.append({
            "trial_id": row.get("trial_id", ""),
            "split": row.get("split", ""),
            "enroll_sec": float(row["enroll_sec"]),
            "label": int(row["label"]),
            "trial_type": row.get("trial_type", ""),
            "score": score,
            "enroll_speaker_id": row.get("enroll_speaker_id", ""),
            "test_speaker_id": row.get("test_speaker_id", ""),
        })

    return pd.DataFrame(rows), skipped

baseline_scores, baseline_skipped = score_trials(eval_trials, baseline_embs)
finetuned_scores, finetuned_skipped = score_trials(eval_trials, finetuned_embs)

baseline_scores["model"] = "baseline"
finetuned_scores["model"] = "finetuned"

baseline_scores.to_csv(EVAL_SAVE_DIR / "baseline_trial_scores.csv", index=False)
finetuned_scores.to_csv(EVAL_SAVE_DIR / "finetuned_trial_scores.csv", index=False)

print("baseline_scores:", baseline_scores.shape, "skipped:", baseline_skipped)
print("finetuned_scores:", finetuned_scores.shape, "skipped:", finetuned_skipped)

score trials:   0%|          | 0/30000 [00:00<?, ?it/s]

score trials:   0%|          | 0/30000 [00:00<?, ?it/s]

baseline_scores: (30000, 9) skipped: 0
finetuned_scores: (30000, 9) skipped: 0

In [ ]:

# =========================
# 12. Metrics
# =========================
def compute_eer(labels, scores):
    labels = np.asarray(labels).astype(int)
    scores = np.asarray(scores).astype(float)

    thresholds = np.unique(scores)
    thresholds = np.concatenate([[scores.max() + 1e-6], thresholds[::-1], [scores.min() - 1e-6]])

    pos = labels == 1
    neg = labels == 0
    n_pos = max(pos.sum(), 1)
    n_neg = max(neg.sum(), 1)

    fars = []
    frrs = []

    for th in thresholds:
        pred_pos = scores >= th
        fa = np.logical_and(pred_pos, neg).sum()
        fr = np.logical_and(~pred_pos, pos).sum()
        fars.append(fa / n_neg)
        frrs.append(fr / n_pos)

    fars = np.asarray(fars)
    frrs = np.asarray(frrs)

    idx = int(np.argmin(np.abs(fars - frrs)))
    eer = float((fars[idx] + frrs[idx]) / 2.0)
    return eer, float(thresholds[idx])


def tar_at_far(labels, scores, target_far):
    labels = np.asarray(labels).astype(int)
    scores = np.asarray(scores).astype(float)

    thresholds = np.unique(scores)
    thresholds = np.concatenate([[scores.max() + 1e-6], thresholds[::-1], [scores.min() - 1e-6]])

    pos = labels == 1
    neg = labels == 0
    n_pos = max(pos.sum(), 1)
    n_neg = max(neg.sum(), 1)

    best_tar = 0.0
    best_far = 0.0
    best_th = float(thresholds[0])

    for th in thresholds:
        pred_pos = scores >= th
        far = np.logical_and(pred_pos, neg).sum() / n_neg
        tar = np.logical_and(pred_pos, pos).sum() / n_pos
        if far <= target_far and tar >= best_tar:
            best_tar = float(tar)
            best_far = float(far)
            best_th = float(th)

    return best_tar, best_far, best_th


def summarize_scores(df, model_name):
    results = []

    for enroll_sec, g in df.groupby("enroll_sec"):
        labels = g["label"].to_numpy()
        scores = g["score"].to_numpy()
        eer, eer_th = compute_eer(labels, scores)

        row = {
            "model": model_name,
            "enroll_sec": float(enroll_sec),
            "n_trials": int(len(g)),
            "n_pos": int((labels == 1).sum()),
            "n_neg": int((labels == 0).sum()),
            "eer": eer,
            "eer_threshold": eer_th,
            "pos_score_mean": float(scores[labels == 1].mean()) if (labels == 1).any() else None,
            "neg_score_mean": float(scores[labels == 0].mean()) if (labels == 0).any() else None,
        }

        for tfar in TARGET_FARS:
            tar, far, th = tar_at_far(labels, scores, tfar)
            row[f"tar_at_far_{tfar}"] = tar
            row[f"actual_far_at_far_{tfar}"] = far
            row[f"threshold_at_far_{tfar}"] = th

        results.append(row)

    return pd.DataFrame(results)

baseline_summary = summarize_scores(baseline_scores, "baseline")
finetuned_summary = summarize_scores(finetuned_scores, "finetuned")
summary = pd.concat([baseline_summary, finetuned_summary], ignore_index=True)

summary_path = EVAL_SAVE_DIR / "verification_summary_by_enroll_sec.csv"
summary.to_csv(summary_path, index=False)

display(summary)
print("saved:", summary_path)

,model,enroll_sec,n_trials,n_pos,n_neg,eer,eer_threshold,pos_score_mean,neg_score_mean,tar_at_far_0.01,actual_far_at_far_0.01,threshold_at_far_0.01,tar_at_far_0.05,actual_far_at_far_0.05,threshold_at_far_0.05,tar_at_far_0.1,actual_far_at_far_0.1,threshold_at_far_0.1
0,baseline,1.0,7587,1900,5687,0.288399,0.321038,0.399039,0.253393,0.118947,0.009847,0.572986,0.306316,0.049938,0.474161,0.449474,0.099877,0.421987
1,baseline,2.0,7476,1868,5608,0.279433,0.318839,0.400159,0.250757,0.126338,0.009986,0.570719,0.318522,0.049929,0.470260,0.472698,0.099857,0.416157
2,baseline,3.0,7434,1857,5577,0.289738,0.322451,0.398605,0.253062,0.127625,0.009862,0.568739,0.303716,0.049848,0.475195,0.438341,0.099874,0.423816
3,baseline,5.0,7503,1875,5628,0.274149,0.344559,0.425651,0.268098,0.128000,0.009950,0.586673,0.337067,0.049929,0.493363,0.489600,0.099858,0.441671
4,finetuned,1.0,7587,1900,5687,0.253710,0.260367,0.399535,0.076541,0.121053,0.009847,0.638038,0.360526,0.049938,0.492533,0.506316,0.099877,0.416304
5,finetuned,2.0,7476,1868,5608,0.253746,0.259127,0.399109,0.077918,0.126874,0.009986,0.640324,0.350642,0.049929,0.493734,0.494111,0.099857,0.418466
6,finetuned,3.0,7434,1857,5577,0.256907,0.255924,0.398745,0.075658,0.117932,0.009862,0.653445,0.329025,0.049848,0.508584,0.501346,0.099874,0.417058
7,finetuned,5.0,7503,1875,5628,0.233093,0.281895,0.431108,0.079362,0.136000,0.009950,0.655715,0.360533,0.049929,0.522873,0.526933,0.099858,0.436755

saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/verification_summary_by_enroll_sec.csv

In [ ]:

# =========================
# 13. Baseline vs fine-tuned comparison
# =========================
comparison_rows = []

for enroll_sec in sorted(summary["enroll_sec"].unique()):
    b = summary[(summary["model"] == "baseline") & (summary["enroll_sec"] == enroll_sec)].iloc[0]
    f = summary[(summary["model"] == "finetuned") & (summary["enroll_sec"] == enroll_sec)].iloc[0]

    row = {
        "enroll_sec": float(enroll_sec),
        "baseline_eer": float(b["eer"]),
        "finetuned_eer": float(f["eer"]),
        "eer_delta_finetuned_minus_baseline": float(f["eer"] - b["eer"]),
        "eer_improved": bool(f["eer"] < b["eer"]),
    }

    for tfar in TARGET_FARS:
        col = f"tar_at_far_{tfar}"
        row[f"baseline_{col}"] = float(b[col])
        row[f"finetuned_{col}"] = float(f[col])
        row[f"{col}_delta"] = float(f[col] - b[col])

    comparison_rows.append(row)

comparison = pd.DataFrame(comparison_rows)
comparison_path = EVAL_SAVE_DIR / "baseline_vs_finetuned_comparison.csv"
comparison.to_csv(comparison_path, index=False)

display(comparison)
print("saved:", comparison_path)

,enroll_sec,baseline_eer,finetuned_eer,eer_delta_finetuned_minus_baseline,eer_improved,baseline_tar_at_far_0.01,finetuned_tar_at_far_0.01,tar_at_far_0.01_delta,baseline_tar_at_far_0.05,finetuned_tar_at_far_0.05,tar_at_far_0.05_delta,baseline_tar_at_far_0.1,finetuned_tar_at_far_0.1,tar_at_far_0.1_delta
0,1.0,0.288399,0.253710,-0.034689,True,0.118947,0.121053,0.002105,0.306316,0.360526,0.054211,0.449474,0.506316,0.056842
1,2.0,0.279433,0.253746,-0.025687,True,0.126338,0.126874,0.000535,0.318522,0.350642,0.032120,0.472698,0.494111,0.021413
2,3.0,0.289738,0.256907,-0.032831,True,0.127625,0.117932,-0.009693,0.303716,0.329025,0.025310,0.438341,0.501346,0.063005
3,5.0,0.274149,0.233093,-0.041056,True,0.128000,0.136000,0.008000,0.337067,0.360533,0.023467,0.489600,0.526933,0.037333

saved: /content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/baseline_vs_finetuned_comparison.csv

In [ ]:

# =========================
# 14. Save metadata and list outputs
# =========================
meta = {
    "run_id": RUN_ID,
    "drive_data_dir": str(DRIVE_DATA_DIR),
    "data_zip_path": str(DATA_ZIP_PATH),
    "finetuned_nemo_path": str(FINETUNED_NEMO_PATH),
    "baseline_model_name": BASELINE_MODEL_NAME,
    "max_trials_per_enroll_sec": MAX_TRIALS_PER_ENROLL_SEC,
    "eval_trials_path": str(EVAL_TRIALS_PATH),
    "n_unique_audio_paths": len(unique_audio_paths),
    "baseline_embedding_failures": len(baseline_failures),
    "finetuned_embedding_failures": len(finetuned_failures),
    "eval_save_dir": str(EVAL_SAVE_DIR),
}
meta_path = EVAL_SAVE_DIR / "eval_meta.json"
meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

print(json.dumps(meta, ensure_ascii=False, indent=2))
print("\nOutputs:")
for p in sorted(EVAL_SAVE_DIR.rglob("*")):
    if p.is_file():
        print(p)

{
  "run_id": "eval_20260427_053001",
  "drive_data_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터",
  "data_zip_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_local_subset_small.zip",
  "finetuned_nemo_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_finetune_runs/titanet_20260427_032738/titanet_small/titanet_small_finetuned_final.nemo",
  "baseline_model_name": "titanet_small",
  "max_trials_per_enroll_sec": 0,
  "eval_trials_path": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/eval_trials_used.csv",
  "n_unique_audio_paths": 3221,
  "baseline_embedding_failures": 0,
  "finetuned_embedding_failures": 0,
  "eval_save_dir": "/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001"
}

Outputs:
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/baseline_embedding_failures.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/baseline_trial_scores.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/baseline_vs_finetuned_comparison.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/eval_meta.json
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/eval_trials_used.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/finetuned_embedding_failures.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/finetuned_trial_scores.csv
/content/drive/MyDrive/랭체인 AI 영상객체탐지분석 플랫폼 구축/오브콜스(Of-Calls)/화자검증 데이터/titanet_eval_runs/eval_20260427_053001/verification_summary_by_enroll_sec.csv